cmake/SQLite/CMakeLists.txt
We only want to dllexport when building shared, else executables that
link against the static library will reexport the exports.
=> Don't dllexport when building static

.ci/templates/android-sdk.yml
CMake's cross-compilation detection is currently not setup for testing
with the explicit target.  We need to force the compiler until that is
fixed.
=> SDK: attempt to force the android SDK Swift compiler

cmake/caches/android-aarch64-swift-flags.cmake, cmake/caches/android-armv7-swift-flags.cmake, cmake/caches/android-i686-swift-flags.cmake, cmake/caches/android-x86_64-swift-flags.cmake
Ensure that we push `CMAKE_Swift_COMPILER_TARGET` to the sub-configure.
This has been fixed in CMake, but provide compatibility for older CMake
versions.
=> android: workaround CMake bug

utilities/Download-SwiftArtifacts.ps1
The WinSDK build is hard coded to a specific build where Windows x64
succeeded :(. Since the previous build has been removed, this updates to
one still exists.
=> Update the WinSDK build

.ci/toolchain-vs2017-amd64.yml
In Windows, CMake FindPythonInterpr uses the registry to find Python if none if provided. Instead of leaving the decision to chance of which Python has written last into the registry, pass the Python found by UsePythonVersion into CMake.
To allow both Unix and Windows, and pipelines that finds an specific Python or not, the template parameter is optional and expands or not into a CMake parameter. This should keep the working pipelines the same, while modifying the failing pipeline to work.
=> Pass the Python executable found by UsePythonVersion to CMake.

.ci/azure-pipelines-aws-agent.yml, .ci/templates/toolchain.yml, .ci/toolchain-darwin-x64.yml, .ci/toolchain-linux-x64.yml, .ci/toolchain-vs2017-amd64.yml, .ci/toolchain-vs2019-amd64.yml
This introduces a new set of variables (core.branch, controlling the
LLVM tree, and branch controlling the swift branches) to enable reusing
the configuration across different branches.
=> toolchain: setup the ability to branch the toolchain **NO_CI**

.ci/toolchain-vs2017-amd64-facebook.yml, .ci/toolchain-vs2019-amd64-facebook.yml
This will need removing the existing schedules in the UI for the VS2017 build.
I don’t know how to test this, but the VS2017 pipeline will use the UI, so that one will not break, and we can see if I screw up the syntax in the VS2019 pipeline (which has no schedules in the UI at the moment).
=> Provide schedules in cron format in YAML.

.ci/templates/windows-sdk.yml, .ci/windows-sdk-facebook-vs2017.yml, .ci/windows-sdk-facebook-vs2019.yml, .ci/windows-sdk.yml
The SDK should be built with the associated toolchain, so make a
parameter for that.
=> SDK: make pipeline a substitution

.ci/curl.yml, .ci/libxml2.yml, .ci/sqlite3.yml, .ci/templates/curl.yml, .ci/templates/libxml2.yml, .ci/templates/sqlite3.yml, .ci/templates/zlib.yml, .ci/zlib.yml
This moves everything to azure, uses templates to build the images.
This simplifies the dependency builds.  It may also enable us to finally
add Linux arm, aarch64 builds.
=> dependencies: template most dependencies, move to Azure

.ci/linux-sdk.yml, .ci/templates/android-sdk.yml, .ci/templates/libxml2.yml, .ci/templates/linux-sdk.yml, .ci/templates/windows-sdk.yml
- use BinariesDirectory for build
- use SourcesDirectory for sources
- use PublishPipelineArtifacts to publish
- use DownloadPipelineArtifacts to consume
=> xml2: improvements

.ci/toolchain-vs2017-amd64-facebook.yml, .ci/toolchain-vs2019-amd64-facebook.yml, .ci/windows-sdk-facebook-vs2017.yml, .ci/windows-sdk-facebook-vs2019.yml
Since there's only one machine in the pools for VS2017 and VS2019, builds every 1h30min were a little bit too much for the machine, since the SDK was also build in the same machine and both of them take around 2 hours, so the builds were starting to queue up.
Move the toolchain builds around 2 hours apart, which should avoid the queueing. Also move the Build Completion triggers to YAML to have them under source control management.
=> [FB] Spread out builds. Move Build Completion trigger to YAML.

.ci/toolchain-vs2017-amd64-facebook.yml, .ci/toolchain-vs2019-amd64-facebook.yml
Use multi-stage builds to tie the triggers together.  This reduces the
number of pipelines and keeps the triggers tied together.
=> Facebook: collapse Facebook jobs into stages

cmake/caches/windows-x86_64-swift-flags.cmake
`CMAKE_Swift_LINK_LIBRARY_FLAG` is not cached without `CACHE` directive.
=> Cache CMAKE_Swift_LINK_LIBRARY_FLAG

.ci/templates/windows-sdk.yml, cmake/caches/windows-x86_64-swift-flags.cmake
An attempt to resolve #160 
Basic ideas:
- CMake cache for Swift builds is modified to allow to specify direct StdLib binaries directory instead of SDK installation path. Existing behavior is preserved (perhaps). This prevents re-build steps from conflicting with already installed binaries.
- Stdlib, libdispatch, Foundation, XCTest are built in a row without testing support, then installed and published.
- libdispatch is reconfigured for testing and tested after publishing.
- As well as Foundation.
Checked this approach locally with custom build script. Let's see how actual pipelines will react.
=> Publish non-test SDK components on Windows

.ci/templates/toolchain.yml, .ci/templates/windows-sdk.yml
Seems that in a multi-stage pipeline, the collectionId and the definitionId in each of the stages is shared. Azure uses those to find out which repository to look for a manifest file. When the two stages have different repository lists, it seems that the previous work directory is discarded. Since both stages had different repository lists, one stage was overriding the other all the time. Since GC doesn't happen (because there's no maintenance), the file system was being filled all the time.
In theory.
=> Match the repository usage in both stages of the build.

.ci/templates/windows-sdk.yml
This enables speculative devirtualization for Foundation builds.
Speculative devirtualization was disabled by default in [5285bf7200d2999812a79df35ff2eebd41cc7ee7](https://github.com/apple/swift/commit/5285bf7200d2999812a79df35ff2eebd41cc7ee7), and since then Foundation tests crash rate noticeably increased.
Unfortunately, CMake has no way to append to `CMAKE_Swift_FLAGS` using only command line arguments. I had to specify some additional flags from caches file. Hope it didn't ruin quotes.
=> sdk, windows: workaround for Foundation crashes

wix/windows-runtime.wxs, wix/windows-toolchain.wxs
Without this change, the value added to the PATH will not be property rooted (i.e. it is missing the "C:" part at the beginning). This prevents the computer from finding either `swiftc.exe` or the Swift runtime binaries, making the files installed by these packages rather useless. Manually fixing the PATH using System Properties will work, but I wouldn’t recommend it as then the uninstaller will be unable to correctly remove the problematic entries (as the exact values it searches for will no longer exist).
I ran into this problem after installing the 5.2 compile release from this repo, and trying to compile the HelloWorld example project in swift-build-examples. I am not 100% positive that this is the correct fix, because I don’t (yet) know how to build the installers from scratch …
=> Use correct property name in PATH setter

wix/windows-toolchain.wxs
Add the lldb site-package for Python bindings to the installed image.
This was pointed out as missing by @mikkeyboi which prevents the use of
the installer image for setting up a jupyter notebook.
=> installer: add LLDB python scripts to installer

.ci/templates/windows-sdk.yml
The `CURL_DIR` will reference the build tree potentially which may be
different than this tree.  Use the manually specified paths instead.
=> Windows: avoid `CURL_DIR` to repair the build

.ci/templates/linux-sdk.yml, .ci/templates/windows-sdk.yml
This should hopefully restore the 5.2 windows builds.
=> CI: remove additional usage of `CURL_DIR`

.ci/templates/android-sdk.yml
For some reason the `CMAKE_HAVE_LIBC_PTHREAD` is failing on the builder.
Force the setting to repair the build.
=> android: force configuration

.ci/macOS-tensorflow.yml, .ci/templates/macos-sdk.yml, .ci/templates/windows-sdk.yml, .ci/templates/xctoolchain.yml, wix/windows-sdk.wxs, wix/windows-tensorflow.wixproj, wix/windows-tensorflow.wxs
Update the references to the TensorFlow version to 2.2.0-rc1.  This
update sets the stage for building the x10 library target.
=> TensorFlow: update rules for TensorFlow 2.2.0-rc1

cmake/caches/org.compnerd.dt.cmake
This enables clangd in the toolchain as it is useful for IDE
integration.  If we are able to include this without exceeding the
timing on the azure hosts, a follow up change would be needed to package
that into the MSI and installer.
Resolves: #196
=> caches: enable clangd builds

.ci/templates/windows-sdk.yml
The swift-apis build requires an additional parameter to find the
TensorFlow headers for the `CTensorFlow` module.
=> TensorFlow: attempt to repair the swift-apis build

docs/GettingStartedWindows.md
Found a small spelling mistake in the GettingStartedWindows doc. Fixed it.
=> Fixing spelling in getting started doc (Windows)

.ci/vs2019.yml
Repair the Android SDK build which requires additional variables to find
ICU.
=> VS2019: add additional variables for Android SDK builds

.ci/templates/icu-deb.yml
Use a variable to reference the ICU version across the job rather than
hardcoding the version in various sites.  This allows for an easier
upgrade process.
=> CI: switch to variable for ICU version

README.md
I don't know if I'm alone in this opinion, but it was hard for me to understand what exactly swift-build does. At least the available project description "Alternate Swift Builds" doesn't tell me much about it, `README.md` only contains links to packages and "Getting started" guides (getting started with what exactly?), but there is no detailed description in `README.md` itself. Was its purpose just to provide packages for Windows (it probably was in the past)? How is Android or TensorFlow packaging related then? Why are there references to Debian packaging?
Now after I was pointed to the way that CI is set up for swift-build, I think it makes a bit more sense to me. This PR is primarily meant to start a discussion on how front facing documentation of swift-build could be improved. I look …
=> Clarify the purpose of swift-build in README.md

.ci/macOS-tensorflow.yml, .ci/macOS.yml, .ci/templates/android-sdk.yml, .ci/templates/icu-deb.yml, .ci/templates/linux-sdk.yml, .ci/templates/macos-sdk.yml, .ci/templates/toolchain.yml, .ci/templates/windows-sdk.yml, .ci/ubuntu-18.04-flowkey.yml, .ci/ubuntu-18.04-google.yml, .ci/vs2017-facebook.yml, .ci/vs2017.yml, .ci/vs2019-facebook.yml, .ci/vs2019-google.yml, .ci/vs2019-master-next.yml, .ci/vs2019-swift-5.2.yml, .ci/vs2019-swift-5.3.yml, .ci/vs2019-tensorflow.yml, .ci/vs2019.yml
Hoist the ICU version selection to metadata on the branch.  This allows
us to use different versions of ICU for different builds.  This is
required in order to bump to ICU 67.
=> CI: externalize ICU configuration

.ci/templates/toolchain.yml
This should speed up the checkout and hopefully reduce disk space usage.
=> toolchain: try cloning with depth 1 for builds

docs/GettingStartedWindows.md
Fixes https://github.com/compnerd/swift-build-examples/issues/20. As pointed out by @compnerd, the build command may fail if a drive name is not provided for the compiler. `%SystemDrive%` was chosen to give new users the largest chance of success when compiling.
=> Update Windows docs to use the system drive to avoid compile failures

.ci/templates/windows-devtools.yml
This PR re-enables the Swift TSC build on Windows which is fixed in https://github.com/apple/swift-tools-support-core/pull/98.
Since TSC depends on SQLite3 now, this PR also adds the required CMake arguments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/compnerd/swift-build/255)
=> CI: re-enable TSC build on Windows

cmake/caches/curl-windows.cmake
`CMAKE_USE_WINSSL` was renamed to `CMAKE_USE_SCHANNEL`. Providing old option is considered an error now.
https://github.com/curl/curl/pull/5795
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/compnerd/swift-build/257)
=> Adopt renamed CURL CMake option

.ci/templates/devtools-msi.yml, .ci/vs2019-google.yml, .ci/vs2019.yml
Now that we have s-p-m working sufficiently on Windows, attempt to
package that into an MSI for inclusion into the toolchain image.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/compnerd/swift-build/279)
=> CI: attempt to package devtools into a MSI

.ci/vs2019-swift-5.3.yml
Unfortunately, the developer tools work never was completed sufficiently
for a 5.3 release.  Remove the unnecessary stage from the build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/compnerd/swift-build/281)
=> CI: remove devtools stage from 5.3 builds

wix/windows-devtools.wxs
Add the Yams binaries to the MSI image which is required for s-p-m.
Fixes: #282
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/compnerd/swift-build/283)
=> WIX: include Yams in devtools MSI

.ci/templates/windows-sdk.yml, .ci/vs2019-swift-5.3.yml
This adds a symbolic link for the swiftc that is attempted to be
executed due to the incorrect extension check in the build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/compnerd/swift-build/290)
=> build: add a workaround symlink for 5.3 builds

wix/windows-sdk.wxs
Adjust the layout to allow the default resource path to be sufficient to
find the modules.  This reduces the flags necessary for Windows to
`-sdk %SDKROOT%`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/compnerd/swift-build/295)
=> build: further tweak layout

wix/windows-sdk.wixproj, wix/windows-sdk.wxs
This is a workaround for the 5.3 release to make `-sdk %SDKROOT%` be
sufficient for using the Swift compiler.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/compnerd/swift-build/296)
=> WIX: duplicate CF headers for flag handling

.ci/templates/sdk-msi.yml, wix/windows-sdk.wixproj, wix/windows-sdk.wxs
Remove the CoreFoundation headers from the installation as they are no
longer required for mainline.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/compnerd/swift-build/297)
=> WIX: exclude CF headers for newer toolchains

utilities/swift-build.py
This allows this to be more easily used from a CI environment where the print just spits out 50k lines of download progress. The printing had to be moved to a separate function due to the lambda.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/compnerd/swift-build/310)
=> Add quiet option

wix/windows-sdk.wixproj, wix/windows-sdk.wxs
This allows the headers to be picked up implicitly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/compnerd/swift-build/314)
=> WIX: move tensorflow headers to `usr/include`

default.xml
In preparation for moving from master to trunk as the default branch and
to mirror the many repositories changing to main as the default branch,
update the repo manifest default branch to `main`.  Propagate the
existing default revision through the rest of the repositories.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/compnerd/swift-build/325)
=> repo: update default revision

.ci/templates/toolchain-msi.yml, .ci/vs2019-swift-5.4.yml, wix/windows-toolchain.wixproj, wix/windows-toolchain.wxs
This adds the `_InternalSwiftSyntaxParser` to the toolchain properly.
This is used by swift-format through the SwiftSyntax package.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/compnerd/swift-build/338)
=> WIX: add `_InternalSwiftSyntaxParser` module

.ci/templates/sdk-msi.yml
Repair the packaging for the 5.3 release to include the CoreFoundation
headers as that release did not use the `@_imlementationOnly` imports.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/compnerd/swift-build/341)
=> CI: correct parameter for CF headers

.ci/templates/windows-devtools.yml, .ci/templates/windows-sdk.yml, .ci/vs2019-google.yml
We can get away with a shallow fetch, use that instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/compnerd/swift-build/343)
=> CI: avoid full clones for the devtools and SDK steps

wix/windows-devtools.wxs
Ensure that we checksum the crypto debug modules.  Add a guid for the
debug info component for the package description.  This largely doesn't
impact anything as the debug information is not currently packaged.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/compnerd/swift-build/351)
=> WIX: correct debug info package for developer tools

.ci/macOS.yml, .ci/templates/devtools-deb.yml, .ci/templates/icu-deb.yml, .ci/templates/linux-devtools.yml, .ci/templates/linux-sdk.yml, .ci/templates/macos-sdk.yml, .ci/templates/sdk-deb.yml, .ci/templates/toolchain-deb.yml, .ci/templates/toolchain.yml, .ci/templates/windows-devtools.yml, .ci/templates/windows-sdk.yml, .ci/ubuntu-18.04-flowkey.yml, .ci/vs2017-facebook.yml, .ci/vs2017-swift-5.2.yml, .ci/vs2017.yml, .ci/vs2019-devtools.yml, .ci/vs2019-facebook.yml, .ci/vs2019-google.yml, .ci/vs2019-master-next.yml, .ci/vs2019-packaging.yml, .ci/vs2019-swift-5.2.yml, .ci/vs2019-swift-5.3.yml, .ci/vs2019-swift-5.4.yml, .ci/vs2019.yml, default.xml
The swift-apis project is no longer needed as
a) Swift for TensorFlow has been shelved
b) tensorflow/swift-apis can now be built standalone
It would be easy to setup a separate build to build the swift-apis.
Furthermore, the project itself has a GitHub action to build it
pre-commit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/compnerd/swift-build/353)
=> CI: remove tensorflow/swift-apis

.ci/vs2019-swift-5.4.yml
Update the default branch points for the late branched projects in the
5.4 release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/compnerd/swift-build/354)
=> CI: set default branches for late branched 5.4 projects

.ci/templates/toolchain.yml, .ci/templates/windows-devtools.yml, .ci/templates/windows-sdk.yml
Current version (3.20) is known to have some issues with Swift pipelines.
3.19.7 is a last version we had before builds gone red.
I suggest to switch back to 3.19 until we have a new CMake release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/compnerd/swift-build/355)
=> CI: use older cmake (3.19.7)

.ci/templates/toolchain.yml, .ci/templates/windows-devtools.yml, .ci/templates/windows-sdk.yml
I absolutely forgot about non-Windows agents when did #355. We should skip that step on other systems, like macOS, etc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/compnerd/swift-build/356)
=> CI: install cmake on Windows agent only

.ci/templates/toolchain.yml, .ci/templates/windows-devtools.yml, .ci/templates/windows-sdk.yml
I am not sure if this is correct way to check for agent type. Can't find any specific variable for such agents, unfortunately. Looks like the only way is to check agent name. Guessing from recent jobs, there are "Hosted Agent" and "Azure Pipelines N" agents.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/compnerd/swift-build/357)
=> CI: install cmake only on hosted agents

.ci/templates/devtools-msi.yml, wix/windows-devtools.wixproj, wix/windows-devtools.wxs
This updates the devtools packaging to account for the unified module
layout that SPM adopted in apple/swift-package-manager#3464.
=> packaging: update rules for unified package manifest in SPM

docs/GettingStartedWindows.md
Although the lack of official sources, I believe that 10.0.17763.0 is a RedStone *5*, not 4.
Links:
- [Wikipedia](https://en.wikipedia.org/wiki/Windows_10_version_history_(version_1809))
- [Microsoft Forum](https://answers.microsoft.com/en-us/insider/forum/insider_wintp-insider_install-insiderplat_pc/complete-list-of-redstone-5-insider-builds/248dca70-a41f-4f96-a64f-6ce505fb5e33)
=> doc: use correct Windows codename in requirements section

wix/SwiftInstaller/Headers/logging.hh, wix/SwiftInstaller/Headers/swift_installer.hh, wix/SwiftInstaller/Sources/logging.cc, wix/SwiftInstaller/Sources/swift_installer.cc, wix/windows-sdk.wxs
Remove the now extraneous logic as there is a better understanding of
the scheduling sequence and handling of the cleanup.  The last item that
remains to be resolved is the committing of the alterations to the
database.  We know now that there will be a single action executed
deferred, not impersonated, after InstallExecute to ensure that we can
deploy the auxiliary support files.  The elevate privileges should allow
us to also mutate the on-disk database for the cached MSI to allow
tracking of the deployed files so that we can clean them up on the way
out.  The clever idea of using the `RemoveFile` table allows us to avoid
using a custom action for the removal process.
=> Installer: clean up the custom action a bit

wix/windows-bundle.wxs
The repair option is now important for users.  With the ability to
auto-deploy the support files, having the ability to repair will mean
that installation before Visual Studio, or when Visual Studio is
updated, users can simply repair the installation rather than uninstall
and install.
=> installer: enable the repair option for the bundle

.ci/templates/devtools-msi.yml, .ci/templates/windows-devtools.yml, .ci/vs2019-devtools.yml, .ci/vs2019-google.yml, .ci/vs2019-swift-5.4.yml, .ci/vs2019-swift-5.5.yml, .ci/vs2019.yml, wix/windows-devtools.wxs
SPM has grown a dependency on swift-collections, add swift-collections to the
set of packages we build.
=> CI: repair the SPM build on windows

.ci/templates/toolchain.yml
Hope I didn't mess with parentheses. Let's try 3.19.8 for 5.4, and 3.21.3 for others.
=> Use older CMake for 5.4 and newer CMake for other branches

.ci/templates/toolchain.yml
Reverts compnerd/swift-build#382
Parameters are not permitted in the condition clause for a script.
=> Revert "Use older CMake for 5.4 and newer CMake for other branches"

.github/workflows/swift-toolchain.yml
The next phase of the build is the SDK (stdlib, libdispatch, Foundation,
XCTest).  This should allow building x86 and x86_64 SDKs.
=> CI: extend the swift toolchain build

.github/workflows/swift-toolchain.yml
This adds the SourceKit-LSP VSCode plugin to the build.  We should be able to
package this up into the final installer to create the completely sealed
installation.
=> GHA: add in builds for the VSCode plugin for SourceKit-LSP

.github/workflows/swift-toolchain.yml
Because ICU is a dependency in the runtime and Foundation, we dynamically link
against it.  Additionally, the data is fairly large and thus is shared across
the two.  This begins the packaging for building the installer.
=> GHA: add a packaging phase for ICU

.github/workflows/swift-toolchain.yml
We currently only package the amd64 toolchain as the toolchain packaging assumes
that we have SourceKit and _InternalSwiftSyntaxParser, which currently do not
build on ARM64.
=> GHA: begin packaging the toolchain

.github/workflows/swift-toolchain.yml
Build SQLite as part of the toolchain build as it is a dependency for llbuild
and SPM.  This will be used in the devtools build.
=> GHA: build sqlite

.github/workflows/swift-toolchain.yml
Add the builds for Swift Package Manager (and its dependency tree) and
SourceKit-LSP (excluding the VSCode plugin).  This builds the rest of the
installer components for a full toolchain build.
=> GHA: begin sketching out the devtools additions

.github/workflows/swift-toolchain.yml
This adds the packaging steps for the runtime and SDK.  They are two halves of
the same build: the runtime is the redistributable portion of the SDK, and the
SDK is the developer component.  We package them in a single step as they are
packaging subets of the same files, and it does not seem valuable to spin up a
new environment to package up a different subset of the files.
=> GHA: package the SDK and runtime

.github/workflows/swift-toolchain.yml
Add the packaging step for the developer tools MSI.  This is the final step
before we can start building an installer.
=> GHA: package devtools

.github/workflows/swift-toolchain.yml
This finally constructs the installer bundle for the toolchain installer.  With
the exception of code-signing, this should be comparable to the results from
Azure.
=> GHA: build the installer bundle

.github/workflows/swift-toolchain.yml
This creates a smoke test phase that can be used to validate the installer
bundle.  This avoids the need for manual validation.
=> GHA: add a smoke test phase

.github/workflows/swift-toolchain.yml
These are largely static, so move them into environment variables to
reduce the number of parameters which are limited to add additional ones
for the rest of the toolchain build.
=> GHA: move dependency revisions into hardcoded values

.ci/templates/windows-devtools.yml, .ci/vs2019-devtools.yml, .ci/vs2019-google.yml, .ci/vs2019-swift-5.4.yml, .ci/vs2019-swift-5.5.yml, .ci/vs2019.yml
This adds a build of swift-system and wires it up to its dependencies on
Azure for the nightlies to pick up in preparation for the eventual
dependency.
=> CI: add swift-system to the devtools build

.github/workflows/swift-toolchain.yml
Add a build of SwiftSystem and wire it up to its dependents in
preparation for a new dependency being introduced.  This will still need
a separate change for packaging which can occur after we are sure that
we can build properly.
=> GHA: enable swift-system in the devtools build

build.cmd
According to the actual directory tree and installer rules, we have to look for internal modules in `%ToolchainInstallRoot%\usr\lib\swift\`
=> Fix toolchain modules restructure step in build.cmd

.github/workflows/swift-toolchain.yml
CMake 3.22 fails to generate Foundation build files:
```
CMake Error in CoreFoundation/CMakeLists.txt:
MSVC_RUNTIME_LIBRARY value 'MultiThreadedDLL' not known for this ASM
compiler.
```
I am still not sure _why_ it fails to detect the correct MSVC library flag. The [code related to this option](https://gitlab.kitware.com/cmake/cmake/-/blob/master/Source/cmLocalGenerator.cxx#L1968) seems to be the same as for previous versions. The configuration step has the actual value of `CMAKE_ASM_COMPILE_OPTIONS_MSVC_RUNTIME_LIBRARY_MultiThreadedDLL`  set to `-MD`. But I guess we could give CMake a hint as a workaround.
=> Foundation build workaround for CMake 3.22

.github/workflows/swift-toolchain.yml
Using clang from [official llvm project release](https://github.com/llvm/llvm-project/releases/tag/llvmorg-13.0.0) to build sourcekit and syntaxparser.
=> Install external clang and enable arm64 sourcekit

.github/workflows/swift-toolchain.yml
The SourceKit-LSP plugin has been replaced with the new VSCode repository.  Switch to that as the source for the plugin.
=> CI: switch to vscode-swift repo

.ci/vs2022.yml
Wire up the building of the MSI packages for the x86 SDK, runtime, and
ICU components.
=> VS2022: add in x86 packaging step

.ci/vs2022-swift-5.7.yml
This is workaround for current miscompiling issue with latest MSVC toolset. Until the reason of the issue is known, we could use last known good toolset version.
Please note that I didn't actually test this solution with Pipelines, and I am not sure if it is possible to run build check against this PR. For GitHub Actions it worked well, so I believe this is the way we can fix builds temporarily, but I'd like to apologize in advance for any possible typos or yml syntax errors. I'll be here to fix them in follow-ups.
=> VS2022, 5.7: use VC 14.31 toolset

.ci/vs2022-swift-5.6.yml, .ci/vs2022.yml
Same changes as in #430, but for main and 5.6 branches.
=> VS2022, main and 5.6: use VC 14.31 toolset

.ci/vs2022-swift-5.6.yml, .ci/vs2022-swift-5.7.yml, .ci/vs2022.yml
`start /w` in cmd.exe behaves weirdly with VS installer, i.e. it could wait forever. I got more stable results with powershell `Start-Process` command.
=> vs2022, wait for VS installer, but with powershell

.ci/vs2022.yml
Looks like we would get more stable results by installing all VC toolset archs unconditionally.
Also, I added setup process check for additional safety. I remember from practice that for some reason vs_installer could ignore all wait flags and exit earlier than actual setup finishes.
=> Install tools for all archs

.ci/vs2022.yml
Switch to the CMakeLists.txt from swift-installer-scripts rather than
the local copy.  Enable the static linking and stop the ICU packaging.
=> CI: use static linking for ICU

.ci/vs2022.yml
Enable the i686 Windows SDK and runtime packaging.  These are not fully ready
for consumption due to ABI issues in the compiler, however, the packaging can
be prepared in spite of that.  This lays the groundwork for the platform arch
once the compiler issues are resolved.
=> VS2022: enable packaging the SDK & runtime for i686

.ci/vs2022-swift-5.5.yml, patch/swift-release-5.5.patch
This change basically covers 4 areas:
- Adds `PYTHON_EXECUTABLE` and `SWIFT_WINDOWS_$(platform)_ICU_nnn` parameters for toolchain and SDK respectively.
- Installs and uses VC 14.31 toolset to workaround the issue with latest toolset version.
- Finds and configures external clang-cl to use with some parts of toolchain and sdk.
- Patches Swift project to use external clang-cl.
A bit more details about the last point. The Swift patch is similar to the one that introduced `SWIFT_CLANG_LOCATION` in main Swift branch. The patch also allows to specify `SWIFT_LIBDISPATCH_C/CXX_COMPILER` externally for libdispatch external project, because Dispatch doesn't compile with external clang.
=> Fix 5.5, vs2022

.ci/vs2022-swift-5.5.yml, .ci/vs2022-swift-5.6.yml, .ci/vs2022-swift-5.7.yml, .ci/vs2022.yml
Latest builds are broken because agent uses python x86 for some reason. In the build logs I see this:
```
-- Found Python3: C:/hostedtoolcache/windows/Python/3.10.6/x86/python3.exe (found suitable version "3.10.6", minimum required is "3.6") found components: Interpreter 
```
Let's try to force the x64 version. I didn't actually try this with Swift pipeline, so there are chances it would not help. In theory, `UsePythonVersion` task would set up the requested Python version and add it to the PATH. And then CMake should just pick it up for toolchain config.
=> vs2022: force python x64

.ci/vs2022.yml
Looks like `swift-def-to-yaml-converter` is now `swift-def-to-strings-converter`.
=> Adopt renamed swift-def tool converter

.ci/vs2022.yml
swift-syntax is going to own all of the infrastructure that
generates the syntax nodes, and the legacy libSyntax build
still depends on that infrastructure. To make this hang together,
we need to clone swift-syntax and point the compiler build into it.
This is being a little overly-aggressive by cloning swift-syntax
into strictly more places than is necessary. The idea being
that Swift itself will begin to require the Swift parser in more
parts of the build (cf Doug's changes to enable the "early swift syntax"
stage of the build).
=> Clone swift-syntax Alongside Swift

.ci/vs2022.yml
Tested locally with Visual Studio 17.3.4, it seems the toolset incompatibility problem has gone.
However, this release hasn't been rolled into the runner image yet, so we need to hold on to next release date to verify it on CI.
=> vs2022: use latest MSVC toolset

.ci/vs2022.yml
As of apple/sourcekit-lsp#651 sourcekit-lsp  now
depends on SwiftSyntax for its internal representation of documents.
=> Add SwiftSyntax to the SourceKit-LSP Build

.ci/vs2022.yml
Looks like we need one more tool now.
=> [vs2022] build swift-compatibility-symbols tool

.ci/vs2022.yml, .github/workflows/swift-toolchain.yml
```
dynamic:
2,313,728 SwiftDriver.dll
623,616 Yams.dll
static:
2,712,064 SwiftDriver.dll
```
This saves 225,280 bytes in the actual release build.
=> CI: switch Yams to static linking on Windows

.github/workflows/swift-toolchain.yml
Start trying to enable code-signing for GHA builds for the toolchain package.
=> GHA: enable code signing

build.ps1
- Centralise `-D CMAKE_M=mt` as that is a CMake workaround
- Clean up bleeding whitespace
- Avoid installing static Swift packages
- Support multiple python.exe in Path
=> build: various tweaks

build.ps1
- Append our standard ASM/C/CXX/Swift flags when specific projects need to specify additional ones
- Fix missing CMAKE_C_FLAGS for `Build-IndexStoreDB`
- Remove extra whitespace in concatenating swift flags
=> Consolidate CMAKE_Swift_FLAGS in build.ps1

build.ps1
This allows calling the script with `build -SDKs X64,X86` to build only for a subset of architectures.
=> Add SDKs param to script allowing building a subset of architectures

build.ps1
Introduce the build tools phase for the build locally.  This is required for cross-compilation as well as can help make the native and cross-compilation behave similarly.  Additionally, with multi-configuration builds on the horizon, we can ensure that we always use the release mode builds for the build tools.
=> build script: pre-compile build tools

build.ps1
Add the new tools that were added to clang-tidy, generate them during the build tools phase, setup the toolchain build to use them.
=> build: add new tools and wire them up

build.ps1
Supports specifying which of the `wxs` files should be built on a given invocation.
=> Add $Arch parameter to Build-WiXProject

build.ps1
This flag was missing when compared with the official build. See 
https://github.com/compnerd/swift-build/blob/67af2270d0b605f8c7691e32b2abf5b5bb298cec/.azure/vs2022.yml#L876
=> Specify CMAKE_Swift_COMPILER_TARGET when building the runtime

build.ps1
Avoids a manual copy step.
Depends on https://github.com/apple/swift-corelibs-xctest/pull/433
=> Leverage CMAKE_INSTALL_BINDIR for XCTest

build.ps1
Currently the order is nondeterministic because it's using a hash table.
=> Sort cmake -D's for ToBatch

build.ps1
Due to intricacies of Powershell argument passing, we can't use `Invoke-Program` with a `ps1` script, but in any case it makes sense to not use that function because `Invoke-Program` is only to handle `-ToBatch`, and the batch script version should be calling `VsDevCmd.bat` rather than `Launch-VsDevShell.ps1`.
Also fixed some quoting now that I remember how to escape double quotes in powershell.
=> Fix broken build.ps1 due to Invoke-Program with ps1

.azure/vs2022.yml, .github/workflows/swift-toolchain.yml, build.ps1
Prepares the CI definitions for the migration of the Windows installer to WiX v4, which relies on Nuget and so require a package restore step: https://github.com/apple/swift-installer-scripts/pull/184
=> Add -restore to msbuild invocations for WiX v4 compatibility

build.ps1
Support a `-ProductVersion` parameter which gets passed down when building the WiX projects.
=> build.ps1 -ProductVersion

build.ps1
For consistency with other arch-specific root paths. Also puts the architecture at the top and "msi" as the subfolder.
=> build.ps1: Add $Arch.MSIRoot

build.ps1
We're now able to build the installer on x64 with build.ps1 so enable it.
=> build.ps1: add call to Build-Installer

build.ps1
WiX v4 will enforce `Packages`' `Version` to be numerical, but will allow `Bundle`s' containing semantic versioning suffixes. It's unclear if this is by design, but it results in a way to get detailed version information in the add/remove programs control panel:
Depends on https://github.com/apple/swift-installer-scripts/pull/184 because this does not work with WiX v3
=> build.ps1: Enable semantic versioning for the installer

.azure/vs2022.yml
`restoreNugetPackages` is deprecated, causes a warning, and invokes a separate `nuget.exe`, whereas `-restore` is now natively integrated into `msbuild`, which seems safer for WiX v4 SDK-style projects
=> Switch to explicit msbuild -restore for AzDO build

build.ps1
Adds support for running the same tests as in the Apple CI: swift, dispatch, foundation and xctest. This is controlled by an optional `-Test` parameter which supports a `*` wildcard.
A few swift tests currently fail, but those are known:
```
Failed Tests (14):
Swift(windows-x86_64) :: Concurrency/Runtime/startOnMainActor.swift
Swift(windows-x86_64) :: Interop/Cxx/class/custom-new-operator-irgen.swift
Swift(windows-x86_64) :: Interop/Cxx/class/memory-layout-execution.swift
Swift(windows-x86_64) :: Interop/Cxx/class/memory-layout-silgen.swift
Swift(windows-x86_64) :: Interop/Cxx/stdlib/msvcprt-module-interface.swift
Swift(windows-x86_64) :: Interop/Cxx/stdlib/overlay/custom-collection-module-interface.swift
Swift(windows-x86_64) :: …
```
=> build.ps1: add test running (swift + dispatch + foundation + xctest)

build.ps1
Now that install scripts use WiX v4, we can build WiX projects for arm64.
=> Enable the arm64 installer build

build.ps1
Introduce `$Arch.BinaryRoot` and use it as the uniform binary root for all non-numeric projects. This doesn't make paths longer (`libxml2-2.9.12.x64` vs `x64\libxml2-2.9.12`).
=> build.ps1: Uniformize binary roots for non-numeric projects

build.ps1
We expect the content to be UTF-8, explicitly specify the encoding for the files that are being created.  This is important to enable the use of VSCode.
=> build: ensure that we write out the content in UTF-8

build.ps1
Due to badly replicated fix in the GitHub UI. Oops.
=> build.ps1: Fix bad escaping

build.cmd, build.ps1
Adds `Get-Help` support to `build.ps1`, proxied by `/?` support to `build.cmd`.
Sample output:
```
S:\SourceCache\swift-build>build /?
NAME
S:\SourceCache\swift-build\build.ps1
SYNOPSIS
Builds the Swift toolchain, installers, and optionally runs tests.
SYNTAX
S:\SourceCache\swift-build\build.ps1 [-SourceCache <String>] [-BinaryCache <String>] [-SDKs <String[]>]
[-ProductVersion <String>] [-Test <String[]>] [-Stage <String>] [-ToBatch] [<CommonParameters>]
DESCRIPTION
This script performs various steps associated with building the Swift toolchain:
- Builds the redistributable, SDK, devtools and toolchain binaries and files
- Builds the msi's and installer executable
- Creates a mock installation under S:\Program Files and S:\Library for local toolchain use
- Optionally runs tests for …
```
=> build.ps1: Add help, including /? support for build.cmd

build.ps1
These will support `%SKIP_PACKAGING%` and `%CMAKE_BUILD_TYPE%` in the Swift CI
=> build.ps1: add -SkipPackaging and -BuildType params

build.ps1
From PowerShell, this will work: `& build.ps1 -Test foo,bar` and be interpreted as `$Test = @("foo", "bar")`. However, from cmd, this: `powershell.exe -File build.ps1 -Test foo,bar` will be interpreted as `$Test = @("foo,bar")` and there is no way to disambiguate and pass in a two-entry array. Since we don't expect commas in our array element names, we can work around this in PowerShell by splitting on the comma ourselves.
=> build.ps1: Work around limitations in passing arrays from cmd

build.ps1
This ended up printed literally:
```
[...]
-D CMAKE_Swift_FLAGS_RELEASE=-O ^
-D LLBUILD_SUPPORT_BINDINGS=Swift ^
-D SQLite3_INCLUDE_DIR=S:\Library\sqlite-3.36.0\usr\include ^
-Encoding
UTF8
-D SQLite3_LIBRARY=S:\Library\sqlite-3.36.0\usr\lib\SQLite3.lib
-Encoding
UTF8
"cmake.exe" --build S:\b\4
```
=> build.ps1: Fix extra -Encoding UTF8 in -ToBatch output

build.ps1
The Apple CI cannot write to this path so this changes adds a `$LibraryRoot` parameter to customize that path.
We also cannot fully skip the install step because later build steps require the restructured SDK, so `$SkipInstall` becomes `$SkipRedistInstall` to avoid writing to `S:\Program Files`.
=> build.ps1: Make S:\Library path customizable

build.ps1
Backslashes that make their way into the CMakeCache.txt get interpreted as escapes so convert them to forward slashes before they get to that point.
=> build.ps1: Force forward slashes in CMake defines

build.ps1
For quickness of iteration on toolchain builds using ninja, this redirects the toolchain build to cmake-install directly to the target installed location, specifically for the host architecture.
=> build.ps1: CMake-install the host toolchain in its target installed location

build.ps1
We did not previously default to lld as the default linker for SPM as build.ps1 was intended for development purposes.  With the attempt to migrate the Apple CI to build.ps1, we do need to change the default.
=> build: ensure that we default to lld for SPM

.github/workflows/swift-toolchain.yml
apt-get cache is outdated, pointing to a version of
libxml2-utils that is not available anymore on ubuntu servers.
This PR runs `apt-get update` before `apt-get install`, which
ensures it is always up to date.
=> Fix libxml2-utils dependency fetch

build.ps1
Bring build.ps1 in line with the CI builds which specify the additional parameters to the llvm configuration.  Thanks to @fischman-bcny for pointing out this divergence!
=> build: add missing configuration options to build.ps1

docs/WindowsQuickStart.md
Since `build.ps1` now supports arm64
=> WindowsQuickStart: Add Arm64 components to VS install instructions

.github/workflows/swift-toolchain.yml
This PR came out of a test to see if compressing & uploading the compilers would be faster.
Turns out it's not, but zipping and then uploading takes a bit longer (~9 vs. 8 minutes).
While at it though, let's:
* name GH actions steps, for easier parsing in GH's UI
* drop excluding icu-69.1 - it's not there (anymore)
=> name GH steps for easier parsing in GH's UI & drop icu special casing

.azure/vs2022.yml
This replicates the build tag support for the main branch snapshots.
=> Azure: add build tag support for development builds

build.ps1
The Apple CI clones SPM as `swiftpm` instead of the repo name `swift-package-manager`.
=> Support alternate SPM clone directory name for the Apple CI

build.ps1
Add support for `-Test llbuild` but does not include it in `-Test *` since tests are known to not be Windows-friendly. Current results are:
```
Testing Time: 15.49s
Unsupported:  15
Passed     :  71
Unresolved : 134
Failed     :  12
```
=> build.ps1: Support running LLBuild tests

.github/workflows/swift-format.yml
Update the version of the actions for SwiftFormat workflow to reduce the amount of warnings due to the use of deprecated node.js versions.
=> GHA: update some action versions

build.ps1
This is helpful for testing the packaging process where the toolchain build has been completed previously.  This enables a more rapid testing cycle for just the packaging which is already a long process.
=> build.ps1: introduce a `-SkipBuild` option

build.ps1
`40` chars should give us plenty of space for output filenames! (famous last words)
=> Add workaround for MAX_PATH with object output directories.

.github/workflows/swift-toolchain.yml
Correct a typo that is responsible for applying the tag to the build version information.
=> GHA: correct a typo in the tag

.github/workflows/swift-toolchain.yml
Begin building `swift-format` as part of the toolchain as this is meant to be part of the toolchain distribution on Windows.
=> GHA: add a swift-format build stage for the toolchain

build.ps1
Example failure this prevents:
```
-- The C compiler identification is Clang 16.0.0 with MSVC-like command-line
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: S:/b/1/bin/clang-cl.exe
-- Check for working C compiler: S:/b/1/bin/clang-cl.exe - broken
CMake Error at C:/Program Files/CMake/share/cmake-3.26/Modules/CMakeTestCCompiler.cmake:67 (message):
The C compiler
"S:/b/1/bin/clang-cl.exe"
is not able to compile a simple test program.
It fails with the following output:
Change Dir: S:/b/201/CMakeFiles/CMakeScratch/TryCompile-iqrula
Run Build Command(s):C:/PROGRA~1/MICROS~2/2022/COMMUN~1/Common7/IDE/COMMON~1/MICROS~1/CMake/Ninja/ninja.exe -v cmTC_9369d && [1/2] S:\b\1\bin\clang-cl.exe --target=i686-unknown-windows-msvc  /nologo …
```
=> build.ps1: fail quickly if run in a Developer shell instead of failing 30m later due to architecture mismatch.

build.ps1
This reverts commit b4f6778c08531fc4a5170b9ce83287f72cfd3cfb.
I think the diagnostic was incorrect here and this will only cause warnings. CMake does have the correct logic for shortening when the full path approaches MAX_PATH. I need to figure out why it's not kicking in here.
=> Revert "Add workaround for MAX_PATH with object output directories."

.github/workflows/swift-toolchain.yml
Enable debug info generation and collection for the standard library and the devtools.  Refactor some code to avoid duplication of definitions, hoist the flag computation to a single site.  Selectively extend the flags to push for a bit more performance (e.g. `/Oi`).  Ensure that we are always enabling ICF and performing DCE.
=> GHA: enable additional debug information generation and collection

.github/workflows/swift-toolchain.yml
This temporarily will upload the swift-format MSI as a standalone component as we do not currently repackage the installer.
=> GHA: upload the swift-format MSI as a standalone artifact

.github/workflows/swift-inspect.yml, .github/workflows/swift-toolchain.yml
Build swift-inspect under the installer setup at the end like swift-format.
=> Build swift-inspect in the toolchain workflow.

build.ps1
This adjusts the builds for the SDK to switch to DWARF.  This is problematic in many ways:
- it adds code bloat
- it slows down linking
- it slightly reduces incremental builds
- the debug information is not possible to be saved
- the resultant binaries are in violation of the COFF specification
Given all the issues, this is still valuable as a change to enable easier debugging.  The official builds remain building with CodeView which means that the PDBs can be linked in parallel, we do not bloat the released binaries, while we get a better debugging experience locally.
=> build: use DWARF for the SDK builds

docs/WindowsQuickStart.md
S:\Library\Developer\Platforms\Windows.platform\Developer\SDKs\Windows.sdk\usr\bin doesn't exist.
The runtime dlls are in S:\Program Files\swift\runtime-development\usr\bin.
=> Update the path string in the using the toolchain section.

build.ps1
Create a new global variable to compute the host runtime directory. This is required to execute tools that are built for the toolchain. The long term goal here is to build a small subset of tools using a build of SPM during the toolchain build to enable packaging the set into the toolchain distribution.
=> build: shuffle some state construction

build.ps1
Dwarf is better for Swift but not supported by WinDBG and Windows tooling, so depending on scenarios we may want different combinations of debugging format.
=> Support specifying the debug info format for C/C++ and Swift code

build.ps1
The rules for the packaging have been changed to reflect the split MSIs:
- bld (Build Tools)
- cli (CLI Tools)
- dbg (Debugging Tools)
- ide (IDE Integration Tools)
- sdk (Platform SDKs)
- runtime (Platform runtime)
=> build: use updated project names for packaging

build.ps1
`swift-format` is part of the default toolchain distribution and must be built to be packaged.
=> build: add `swift-format` to the build

build.ps1
DocC is not yet part of the distribution on Windows as we are progressing towards passing the test suite.  However, other products were released before the test suites were completely passing and that would remain an option here.  Begin building this tool as part of the build as it is meant to be part of the distribution.
=> build: add DocC to the default built

build.ps1
This is needed when testing the full packaging rules.  We had accidentally regressed this build.
=> build: repair the build of the ARM64 SDK

build.ps1
Add a wrokaround for RelWithDebInfo builds which use the C++ driver during the bootstrap phase.  The old driver is unable to properly handle the WMO optimization, treating the bitcode improperly.  Disable WMO on RelWithDebInfo builds as a workaround.
=> build: add a workaround for the C++ driver

build.ps1
To avoid hardcoding `CMAKE_CL_SHOWINCLUDES_PREFIX` unless we need it since it can break builds on non-English machines.
=> Add CMake version check for /showIncludes workaround

build.ps1
`&` tells powershell that we're executing a command and not looking for a function.
=> build.ps1: Make cmake invocation explicit for version testing

build.ps1
We shouldn't try to test the `cmake.exe` version without being in a developer command shell because we may be using Visual Studio's `cmake.exe`, which gets added to the path by `Invoke-VsDevShell`.
=> build.ps1: Fix cmake.exe version checks when not in %Path%.

build.ps1
swift-inspect will fail to build in release mode after the dump-arrays PR (https://github.com/apple/swift/pull/66973) due to an llvm bug (https://github.com/llvm/llvm-project/issues/40056). This is a workaround for it.
=> Add a build workaround for the swift-inspect release build

build.ps1
When building on ARM64 ensure that we build the tools as there is no need to have the X64 variant be used for this.
=> build: repair the ARM64 build of ICU on ARM64

.github/workflows/swift-toolchain.yml
We already compute the tag name in the context build, reuse the memoised value rather than re-computing it.  This avoids having the same logic littered across the workflow which is the motivating factor behind the change.
=> GHA: centralise computation of tag name

.github/workflows/swift-toolchain.yml
`-debug-info-format none` is more accurate about disabling the debug information generation.  We would previously generate the debug information for part of the code whereas this should entirely strip debug information.
=> GHA: be more aggressive about disabling debug information

.azure/vs2022.yml, .github/workflows/swift-toolchain.yml, build.ps1
To account for https://github.com/apple/swift-installer-scripts/pull/215
Some follow-up work will be required for the CI since swift-format and swift-lint are now packaged in cli/dbg msi's.
=> Fix paths to wixproj files

.github/workflows/swift-toolchain.yml
With the update to the installer definitions, we'll need to reshuffle the CI to build `swift-format` and `swift-inspect` using the compiler in artifacts rather than running the installer. Until then, comment them out to get the builds green again.
=> Disable swift-format and swift-inspect builds

build.ps1
The installer will copy this module as well, but we failed to deploy it from the staging to the local installation which prevents the local deployment from being used for testing C++ interop.
=> build: deploy CxxShim module on Windows

.azure/vs2022.yml
This attempt uses `build.ps1` as the tool to restructure SDK/Toolchain. While we probably want to avoid using `build.ps1` this way, this still works and proves the concept. I would continue working on standalone restructuring step.
Also, I didn't manage to run the whole pipeline on Azure-hosted agent (i.e. just like original pipeline), because it exceeded 6h quota again😔But testing partially on self-hosted runner demonstrated promising results.
=> Add swift-format stage

build.ps1
There were a couple of commands which were being executed unconditionally.  These need to be emitted as strings when running in the `-ToBatch` mode so that we can replicate the build without executing the script.
=> build: repair the `-ToBatch` functionality

.github/workflows/swift-toolchain.yml
Example invocation: https://github.com/thebrowsercompany/swift-build/actions/runs/5798835944
Artifacts: TODO
=> Upload MSM to release artifacts during swift-toolchain build

.github/workflows/swift-toolchain.yml
Follows up #603 by downloading the MSM from the swift-toolchain.yml action run and uploading it to the GitHub release's artifacts.
Test run: https://github.com/thebrowsercompany/swift-build/actions/runs/5812190767
Result: https://github.com/thebrowsercompany/swift-build/releases/tag/20230809.001-ami contains runtime.amd64.msm
=> Upload runtime MSM to Release artifacts

build.ps1
This can be helpful to diagnose build failures.  Always collect a binlog so that we can analyse the build process later.  Take the opportunity to clean out an unreferenced variable.  One side effect is that the summary view is enabled with the binarylogger, so disable that explicitly.
=> build: collect binlogs on the build

build.ps1
Avoid re-cloning the dependencies for swift-format and swift-docc and reuse the existing checkout using the CI paths.
=> build: attempt to reuse checkouts for building auxtools

build.ps1
Remove the accidental leading `-` in the debug info format that prevented the Release mode builds.
=> build: correct typo in debug info format

build.ps1
Permit re-rooting the build to an alternate drive in the case that `S:` is in use.
=> build: introduce a new `Drive` parameter

build.ps1, docs/WindowsQuickStart.md
Migrate the toolchain to `S:\Program Files\Swift\Toolchains` and drop the `.xctoolchain` suffix.  This is to match an upcoming restructuring of the toolchain installer.  We must URI escape the stage path as spaces are problematic for the installer.
=> build: alter toolchain stage location

build.ps1
This used to prevent creating the pseudo-Program Files structure on the Apple CI, but now we create it anyways so there's no point to keep this flag.
=> Remove $SkipRedistInstall

build.ps1
When properties contain spaces and backslashes, the backslashes are treated as escape characters and must be escaped.  Escape the paths prior to passing them to allow building again.
=> build: adjust the msbuild invocation for spaces

build.ps1
We do want `XCTest-$ProductVersion` at some point, but this must be piped through the installer and `build-toolchain-windows.bat` (if it still exists at that point)
=> Revert to "XCTest-development" naming

build.ps1
The $ImageRoot-based paths (especially SDK) have had reshuffling applied to match a freshly installed toolchain's layout.
main version of #620
=> Use ImageRoot-based paths when building SPM projects

build.ps1
It previously defaulted to a location in the source tree.
=> Set the intermediate path for wixprojs

build.ps1
`Install-Redist` was not called anymore, so the runtime binaries were never copied and the `Build-SPMProject` steps failed because the runtime `%Path%` they referenced was empty.
=> Restore copying the runtime binaries to S:\Program Files

build.ps1
This was causing nuget restore failures because projects were overwriting the same `project.assets.json` file. I thought we were writing to the source tree without this, but it must have been stale files from previous versions of the build, because the installer should now send intermediates to `$(BaseOutputPath)obj\$(MSBuildProjectName)\`, and we override `BaseOutputPath`.
=> build.ps1: Remove the msbuild intermediate directory override

.azure/vs2022.yml
Here we're disabling all optimizations with `/Od`, and then enabling `/Gw /Oi /Oy /Gy /Ob2 /Ot /GF`, which is the same flag set as `/O2` enables, but without "Global Optimizations" (`/Og`).
=> Azure: patch llvm config as temporary workaround for slow arm64 builds

.azure/vs2022-swift-5.9.yml, .azure/vs2022.yml
This is adventurous a little, but should save us about 1Gb+ of space.
Hope I didn't mess the condition. I want this be enabled only for Azure hosted runners, and there seems no other way to detect them.
=> Azure: free space for toolchain install

build.ps1
Reverts compnerd/swift-build#625
The renaming is not yet merged.
=> Revert "Fix reference to the runtime msi"

build.ps1
If a cmake define is an argument string, we need to distinguish tokens containing spaces from multiple tokens. For example, we must be able to pass the below as two command line arguments to cmake:
`-D` `CMAKE_Swift_FLAGS=-sdk "S:/Program Files/Swift/Platforms/Windows.platform/Developer/SDKs/Windows.sdk" -g -Xlinker /DEBUG:DWARF -use-ld=lld-link -Xlinker /INCREMENTAL:NO -Xlinker /OPT:REF -Xlinker /OPT:ICF`
Quoting becomes tricky in this case. We need to quote compiler flags arguments when they contain spaces to keep them a single token, and because of Windows cmd or cmake rules, the quotes need to be escaped with backslashes. Which means that we can't replace all backslashes into forward slashes wholesale.
The solution is to support two kinds of entries in the `$Defines` hashtable: single …
=> Fix quoting in CMake args defines

.azure/vs2022.yml
"Desperate Times Call for Desperate Measures"
Truncating obj files and resetting timestamps to trick Ninja thinking they are not changed, so install step runs as usual.
Here is my success run: https://dev.azure.com/lxbndr/swift-windows/_build/results?buildId=372&view=logs&j=af9f4b2c-adba-5fb9-b92b-bad76b92442e&t=cb4b7c89-a562-5e9e-e8f2-2817ec23f4b4
The environment is synthetic and all input is prebuilt, but the goal was to pass install step without rebuilding whole toolchain.
=> AzDO: truncate intermediate output files to save space

build.ps1
Accounts for changes in https://github.com/apple/swift-installer-scripts/pull/224
=> build.ps1: Update the msbuild installer call

build.ps1
Powershell was binding `-gdwarf` to a `gdwarf` argument, so the `$Value` argument ended up `$null`.
=> Fix appending the -gdwarf flag

build.ps1
Use the architecture specific paths to repair the packaging.  This should repair the packaging after the latest changes to the installer.
=> build: adjust the parameters to packaging

build.ps1
We have additional indicators to the build process to indicate which SDKs and Runtimes are built and should be packaged.  This updates the packaging to account for that.
=> build: indicate that the SDK should be included

build.ps1
The default value is online bundle, which will break the current testing that we have available on swift.org CI.  Default to the offline bundle for now.
=> build: specify bundle flavor

build.ps1
The SDKs are included by the `INCLUDE_[ARCH]_SDK` indicator which was missing the `_SDK` suffix preventing the inclusion.  Correct this to repair the packaging.
=> build: repair the inclusion specifier

build.ps1
Now that we have the MSMs, we do not need the MSIs as the two intents for the MSI was to provide the runtime (which should prefer the MSM) and the installation of the components, which is now possible with the installer once the remaining changes are merged.
=> build: stage the MSMs

build.ps1
The Apple CI build machines only have an older, problematic version of the Windows SDK installed. This will allow us to override it with a more recent downloaded one without having to install it to program files.
I diffed `vsdevcmd` invocations with and without `-winver=none` to figure out which environment variables to set.
=> build.ps1: Support non-installed Windows SDKs

build.ps1
Consistently use the lower case spelling rather than title case.
=> build: normalise `$env` spelling

build.ps1
This introduces the packaging options to integrate DocC into the distribution.
=> build: include DocC into the packaging

build.ps1
The just installed SDK is placed into the SDKInstallRoot not the RuntimeInstallRoot.  Account for this when constructing the new path.
=> build: adjust the library search path

.github/workflows/swift-toolchain.yml
Wire up the arm64 installer release path to allow us to easily download the ARM64 toolchain installers.
=> GHA: publish ARM64 installers

build.ps1
By default `curl` won't create intermediate path directories. It would work on a rerun because `Expand-Archive` creates the directory before failing due to not finding the zip.
=> Fix curl error when running build.ps1 after nuking the binary cache.

build.ps1
These flags should not be combined as they cause the modules to be built incorrectly and remove some of the required library search paths. Repair the standard build for now.
=> build.ps1: `-sdk` and `-resource-dir` are mutually exclusive

build.ps1
With swift switching to FetchContent for swift-syntax, we no longer need to build the dependency initially and instead can rely on the Swift build to build this for us.
=> build.ps1: adjust the build for recent changes

.github/workflows/swift-toolchain.yml
Using sccache should allow us to better re-use the artifacts to help reduce the build times.
=> GHA: setup sccache to allow better builds

.azure/vs2022.yml
Had to move msi and cab files to dedicated dirs before publishing, as Azure only can publish whole directories or single files.
=> Azure: publish cab files alongside with msi's

build.ps1
SourceKit-LSP now has a dependency on Crypto.  Adjust the build rules accordingly.
=> build: adjust for apple/sourcekit-lsp#859

.azure/vs2022.yml, .github/workflows/swift-toolchain.yml, build.ps1
Leverages the new Swift toolchain installer support for integrating the vcredist installer: https://github.com/apple/swift-installer-scripts/pull/250
=> Pass flags to bundle the vcredist installer

.github/workflows/swift-toolchain.yml
The newer versions of python do not include `setuptools` which provides `distutil` which results in failures. Additionally, this ensures that we consistently use the python version.
=> GHA: explicitly select the python interpreter

.azure/vs2022.yml
Also:
- bump dependencies (curl 8.4.0, swift-asn1, swift-certificates, swift-collections, swift-crypto)
- specify `SWIFT_CLANG_LOCATION` unconditionally (not only for arm64 builds)
- adjust VS redist packaging
=> AzDO: use pinned toolchain for early swift-syntax build

build.ps1
This will increase the size of the toolchain but is required to work with the ABI name mismatches on the swift-syntax binaries used across the toolchain and SourceKit-LSP.
=> build: use static linking for swift-syntax temporarily

.github/workflows/swift-toolchain.yml
We will soon need the Swift toolchain for building swift-syntax to support macros. Do this now to allow us access to `clang-cl` to avoid a dependency race condition where dispatch is built before `clang-cl` is built, which seems to have arisen with the rebranch.
=> GHA: install a Swift toolchain to workaround race condition

.azure/vs2022.yml
Adopted latest build process changes:
- llvm branch set to `stable/20230725`
- VS toolset updated to latest version to workaround build issues
- dropped unnecessary t-s-c sqlite configuration parameters
=> AzDO: drop t-s-c sqlite parameters, bump llvm to 20230725

build.ps1
Allows specifying a build step after which the build script invocation should terminate, for example `-BuildTo ToolsSupportCore`.
Currently only supports build steps (including the installer build), and cannot distinguish between different architectures for SDK/runtime projects.
=> build.ps1: Add -BuildTo

build.ps1
We need to stage the MSIs and the Burn engine to simplify the code signing process for the swift.org hosted builds. Simply add the additional copying and the burn detachment to the staging process.
=> build: stage additional artifacts

build.ps1
Create the temporary directory before extracting the burn engine which would otherwise fail.
=> build: ensure that the temporary directory exists

.github/workflows/swift-toolchain.yml
Although these builds are small, the overall time cost is annoying when doing repeated builds.  Attempt to use sccache to amortise some of the cost.
=> GHA: setup sccache for early builds

.azure/vs2022.yml
We have a plenty of steps with conditions, and most of them don't check the job status. This not only looks weird when the job is cancelled or failed, but could lead to (minor) undesirable/unexpected side effects.
=> AzDO: ensure succeeded condition is evaluated

.github/workflows/swift-toolchain.yml
The direct mode can give a nice boost to sccache if the preprocessor is not used.  This might be helpful for us, so lets try enabling it.
=> GHA: attempt to use sccache's direct mode

.github/workflows/swift-toolchain.yml
Template and preserve the `SwiftSyntaxConfig.cmake` to allow us to re-use the existing artifacts as we do with the `build.ps1` based build.
=> GHA: template the SwiftSyntaxConfig.cmake for LSP builds

.github/workflows/swift-toolchain.yml
The addition of the VCRuntime this way requires that we have administrative rights.  Restore the ability to install the toolchain without the administrative rights by disabling the runtime packaging.
=> GHA: disable runtime bundling

.azure/vs2022.yml, .github/workflows/swift-toolchain.yml
This is used by the runtime MSI, not the installer bundle.  This works on the Apple CI as it does a single unified build, whereas we do the piecemeal build to get better control.  Adjust the invocation to match the requirements.
=> CI: Update rules to pass the `VCRedistDir` appropriately

.github/workflows/swift-toolchain.yml
Use the new V4 release of the artifact which should have performance improvements though it will change some of the behaviour.
=> GHA: update the {download,upload}-artifact action

.github/workflows/swift-toolchain.yml
We no longer need to clone additional dependencies which will reduce checkout time.  Additionally, reduce the configuration to reduce overall configuration time as well.
=> GHA: trim the tools phase

.github/workflows/swift-toolchain.yml
The Code Signing certificate is currently expired which is preventing us from releasing builds. Add an option to disable code signing.
=> GHA: optionalise code signing

.github/workflows/swift-toolchain.yml
Use the forked ccache-action to use the latest sccache release. This should allow us to use the direct mode and hopefully get slightly faster builds.
=> GHA: bump sccache to 0.7.4

.github/workflows/release-swift-toolchain-schedule.yml, .github/workflows/swift-toolchain.yml, docs/ReleaseProcess.md
The new workflow reuses the `swift-toolchain.yml` workflow. I tested this workflow at thebrowsercompany/swift-build .
The release workflow builds releases, like Swift 5.10 nightly. As a follow-up, I will add additional logic to not rebuild the release when the toolchain checkout doesn't change.
=> Add a workflow to build Swift 5.10 release on schedule

.github/workflows/release-swift-toolchain-schedule.yml, .github/workflows/swift-toolchain.yml, docs/ReleaseProcess.md
* [GHA workflow] use 'inputs' instead of 'github.event.inputs'
This is needed for making reusable workflow work, and still works with main scheduled workflow
* [GHA workflow] add a workflow to build Swift releases on a schedule
The new releases build job reuses the swift-toolchain workflow
* [docs] update the release process docs to describe how to ensure the release builds on schedule
* [GHA workflow] add a doc note specifying why owner/repo is required
=> 🍒 Add a workflow to build Swift 5.10 release on schedule (#702)

.github/workflows/swift-toolchain.yml
Update the rules to account for the split cmark-gfm build and wire that up into the build. This uses a small hack as the build expects to find the CONFIG form and does not allow for the fallback currently.
=> GHA: revise for split cmark

.github/workflows/swift-toolchain.yml
Build swift-markdown, swift-format with CMake. swift-format is no longer optional, so we must build it and package it.
=> GHA: adjust to CMake built swift-format on Windows

.github/workflows/swift-toolchain.yml
We were missing necessary flags for the linker when building with debug information, preventing the emission of the PDB. This is important to allow us to quickly debug crashes now that we have the symbol server functional.
=> GHA: enable PDB generation for swiftCore, Foundation

.github/workflows/swift-toolchain.yml
The recent GHA build image update seemed to have caused build errors. Unescape the path in the hopes that it fixes it.
=> GHA: attempt to unescape a level of quoting for SDK

.github/workflows/swift-toolchain.yml
Use the `gh` command line tool to generate the release rather than relying on the deprecated actions. This reduces the warning spew on jobs.
=> GHA: migrate away from deprecated actions

.github/workflows/swift-toolchain.yml
This ensures that we do not misrepresent the latest cache entry. Without this, the caches used is subtly incorrect.
=> GHA: do not include timestamp in cache key

.github/workflows/swift-toolchain.yml
Remove the `sccache-` prefix as that is already implicitly added.
=> GHA: adjust key for caches

.github/workflows/swift-toolchain.yml
This backports:
- 363b317c637c02ded0496ffb844030d62aeba94f
- 8c568ff632e4d7d6785f8d95d6ac1fb0529c2240
To 5.10 from main. The motivation is to help clean up the cache storage and prepares for bifurcating the caches per branch.
=> Backport caching changes to 5.10

.github/workflows/swift-toolchain.yml
This version does not currently seem to be available. Revert to the unversioned representation in the hopes to fix the build. The regression which forced the update _should_ be fixed (the latest release has a fix).
=> GHA: unpin the VS tools version

.azure/vs2022.yml
This aligns AzDO build with GHA workflow. Mostly about swift-format and cmark-gfm changes, but there are also many small changes in SDK and devtools CMake configuration, so they are closer to the build flow from `build.ps1` now.
Also
- fixed zlib path in curl configuration
- adjusted devtools build directory for more convenient self-hosted process
- enabled arm64 swift-inspect in auxtools
- enabled arm64 tools packaging
- enabled arm64 installer
- removed arm64 performance hack, as it is in LLVM already
This is quite a big changeset (that's why it comes as a bunch of commits instead of single commit), but it is minimal piece of work which passes build check completely.
=> AzDO: Adopt swift-format and cmark-gfm changes from GHA

.github/workflows/swift-toolchain.yml
Upload the PE files generated by the ArcCore build to the Azure symbol server in addition to the PDBs.
Also make the symbol search pattern explicit as the default wasn't gathering all desired files.
=> [Azure sym server] Upload the DLLs

.github/workflows/swift-toolchain.yml
This reverts commit 0b873dc57350464c6226d68fb8ce19479eb08484.
=> Revert "Pin the gha-setup-swift dependency. (#727)"

.github/workflows/swift-toolchain.yml
This reverts commit e0c2bd9e76b1bd068fda11e99d64317035d9711b.
=> Revert "Pin the gha-setup-swift dependency. (#728)"

.github/workflows/swift-toolchain.yml
SPM has a newly minted dependency on swift-syntax. This needs to be fulfilled and re-building the dependency and statically linking will increase the binary size ~70M (*3). Use dynamic linking to avoid that and to save build time.
=> GHA: re-use the swift-syntax build for SPM

.github/workflows/swift-toolchain.yml
- Remove some unnecessary swift build flags
- Skip vsdevenv setup - it interferes with the link step.
- Place host SDK in different directory
- Download both target and host SDKs
- Duplicate steps to patch misplaced SDK libs
- Split the build command across multiple lines
Fixes thebrowsercompany/swift-build#125
=> Fix arm64 build for swift-inspect

.github/workflows/swift-toolchain.yml
While nuget is preinstalled on GitHub Actions provided Windows images via Chocolatey, it may not be available on custom images.
=> GHA: Explicitly install nuget

.github/workflows/swift-toolchain.yml
The workflow doesn't currently have a pull_request trigger (this decision is specific to the project that runs the workflow) but it's safe to assume that if a pull_request trigger is added, we should skip the snapshot and release steps. This PR adds if-statements to do so.
=> Skip upload steps if the trigger is pull_request

.github/workflows/swift-toolchain.yml
The GitHub runner image update introduced two main problems:
1. VS 17.10 STL introduced a hard requirement on Clang 17, which is not available for any 5.10 toolchain. For now, manually patch `yvals_.core.h` to relax this requirement, but this is brittle.
2. An update in VS 17.10 STL made `mutex`'s constructor `constexpr`, which breaks compatibility between mixing different versions of the STL (reasonable). A `PATH` configuration problem on the GHA image causes the linker picks up an old copy of `vcruntime140.dll` from a Python installation rather than `C:\Windows\system32\vcruntime140.dll`, violating this requirement of the STL. This is fixed in the latest GHA windows image, `20240610.1`, but this hasn't made it to our runners yet, so in the meantime, disable the `constexpr` constructor …
=> Fix swift-toolchain.yml after VS 17.10 upgrade on latest GHA image

.github/workflows/swift-toolchain.yml
`git apply` put this hunk in the wrong spot. The surrounding lines in [the patch](https://patch-diff.githubusercontent.com/raw/thebrowsercompany/swift-build/pull/158.diff) are identical but I would've assumed the line numbers to be taken into account.
Original PR: https://github.com/compnerd/swift-build/pull/743
=> Move Patch yvals_core.h step to the right place in the `compilers` job

.github/workflows/swift-toolchain.yml
`-D_ALLOW_COMPILER_AND_STL_VERSION_MISMATCH` should allow us to workaround the mismatch. This is cleaner than the solution of modifying system headers.
=> GHA: prefer to use a macro over changing the headers

.github/workflows/swift-toolchain.yml
Pulls in some quality of life changes from thebrowsercompany/swift-build:
- Add an input to skip publishing artifacts.
- Pin ccache-action to a version that adds sccache to PATH after installing.
- Make sure Nuget sources are updated before installing python arm64
- Replicate swift_tag inpt for workflow_dispatch
- Don't publish stable.xml when artifact publishing is disabled.
- Don't create releases when artifact publishing is disabled.
compnerd/ccache-action can likely be removed now, as this workflow no longer depends on it and all changes have been upstreamed.
=> Upstream changes from thebrowsercompany/swift-build

.github/workflows/swift-toolchain.yml
Fix broken dry run check and `workflow_call.swift_tag` input
- We should upload if `publish_artifacts == true` rather than if `publish_artifacts != true`. This was missed by mistake when switching from `dry_run=true` which is the opposite.
- Add the required 'type' attribute to `workflow_call.swift_tag`. This wasn't checked before by GitHub because we never actually used workflow_call in thebrowsercompany/swift-build, but now GitHub is complaining that this attribute is missing.
- Default to `publish_artifacts = true` so that we don't break existing scheduled workflows that expect uploads to happened by default.
https://github.com/thebrowsercompany/swift-build/actions/runs/9555537790/job/26338983155
=> Fix broken publish_release artifacts check

.github/workflows/swift-toolchain.yml
Clang 18 is the default version of Clang on GitHub runner images, and has a broken definition of the `__prefetch` intrinsic on arm64 which causes build failures. We can instead use the Clang that comes with the pinned toolchain (Clang 16 on Swift 5.x releases), which does not have this broken definition.
See https://github.com/llvm/llvm-project/pull/93235 for more details.
=> Use toolchain clang to build compilers (fix Clang 18 breakage on arm64)

.github/workflows/swift-toolchain.yml
VS 17.10 introduced a requirement on Clang 17, but the pinned Swift toolchain used to bootstrap the compilers (a 5.10 snapshot) uses Clang 16. We can relax this version requirement with `ALLOW_COMPILER_AND_STL_VERSION_MISMATCH` which needs to be passed via `CMAKE_Swift_FLAGS` when configuring the compilers.
This mirrors the change to build.ps1 in https://github.com/swiftlang/swift/pull/74662
=> Pass -Xcc -D_ALLOW_COMPILER_AND_STL_VERSION_MISMATCH to CMAKE_Swift_FLAGS

docs/WindowsQuickStart.md
Visual Studio does not provide a ARM64 python distribution yet, so indicate that we need a separate installation there.
=> docs: add a note about Python availability on ARM64

.github/workflows/swift-toolchain.yml
Ensure android NDK is installed regardless of runner.
This fixes the workflow on runner images where the NDK is not
installed. It bundles together a few other changes to ensure
CMake is executed correctly and make it easier to diff CMake
log in the GHA UI with the content in swift-toolchain.yml
* Always run gha-setup-vsdevenv even if runners.os != 'Windows'
* It provides us with the path to CMake
* Switch to nttdl/setup-ndk to install the Android NDK.
* Always specify Android-specific MAKE defines, but enable others
iff matrix.os == Android.
* CMAKE_SYSTEM_NAME=${{ matrix.os }} controls which system we're
building for, so there's no need to use matrix.extra_flags for
Android-specific defines. Inlining them ensures powershell
variable expansion works, and makes it easier to copy paste …
=> Install the Android NDK before all steps that need it

.github/workflows/swift-toolchain.yml
All steps that run msbuild, including the new Android packaging steps must install WixToolset.Sdk on non GitHub runners
=> Upstream WixToolset.Sdk Installation

.github/workflows/swift-toolchain.yml
100Mib cache size is not able to fit all entries for the Android ICU build, which leads to manifestation of sccache bug happening in subsequent runs (https://github.com/mozilla/sccache/issues/2092).
=> Bump up the ICU build sccache size

.github/workflows/swift-toolchain.yml
Reduce unnecessary verbosity on the configuration. Always generate the snapshot as we want to track any successful build. Add some whitespace to the release creation script.
=> GHA: tweak workflow configuration

.github/workflows/swift-toolchain.yml
This reorders the options to be inputs first, makes the Android API level lose the asterisk as there is a default value, and infer the snapshot building based on the input.
=> GHA: tweak dispatch workflow inputs further

.github/workflows/swift-toolchain.yml
The SDK and devtools steps on the release/5.10 branch must also use the old version `14.39.33519` of VS build
tools which are still compatible with Clang 16.  
https://github.com/thebrowsercompany/swift-build/actions/runs/9943835623
=>  Install VS build tools 14.39.33519 for sdk and devtools steps on release/5.10

.github/workflows/swift-toolchain.yml
This PR includes two commits to fix the 5.10 release build:
- The first installed VS build tools 14.39.33135 which work with Clang 16
- The second forces the compilers step to use the Clang from the toolchain build.
This was tested downstream in `thebrowsercompany/swift-build` CI.
=> Install VS build tools 14.39.33519 for the compilers step on release/5.10

.github/workflows/swift-toolchain.yml
This lets the compiler build step build
the Android builtins when building the compiler.
=> setup the NDKPATH env when building compiler

default.xml
Fix a typo for swift-nio.
Use main for swift-testing because it doesn't have release branches.
apple/swift-testing:
fatal: couldn't find remote ref refs/heads/release/6.0 apple/swift-testing: sleeping 4.0 seconds before retrying fatal: couldn't find remote ref refs/heads/release/6.0 error: Cannot fetch apple/swift-testing from https://github.com/apple/swift-testing Fetching: 100% (2/2), done in 10.012s
error: Cannot checkout apple/swift-nio: ManifestInvalidRevisionError: revision release/6.0 in apple/swift-nio not found
=> Fix default.xml.

.github/workflows/swift-toolchain.yml
We were miscomputing the SDKROOT which would fail to find necessary modules when trying to build swift-inspect. Correct the computation and simplify the rules a small amount.
=> GHA: correct SDKROOT handling

.github/workflows/swift-toolchain.yml
We would previously download the AMD64 SDK to the wrong location and would thus fail to find the necessary content.
Cherry pick commit https://github.com/compnerd/swift-build/commit/e108a13b914eff4b87c538cefca606933432921d
=> GHA: download the SDK to the proper location

.github/workflows/swift-toolchain.yml
The checkout needs to be updated after the posix_filesystem apinote fix landed in Swift. I needed to switch to my own remote as I could no longer push a new branch into the Apple remote.
=> Update android corelibs-foundation pinned checkout

.github/workflows/swift-toolchain.yml
* fix swift-inspect build
* Use single globbed move-item
Cherry pick commit https://github.com/compnerd/swift-build/commit/61ad739531d63fabe840a9e4eb8af467e0c07c20
=> fix swift-inspect build

.github/workflows/swift-toolchain.yml
Remove the ICU dependency as it has been removed from the repo manifest. This now requires that we use the re-cored Foundation.
=> GHA: remove ICU build after the re-core transition

.github/workflows/swift-toolchain.yml
The pin will no longer be needed since we're switching to swift-foundation
=> [android] checkout unpinned installer script

.github/workflows/swift-toolchain.yml
CURL was updated to 8.9.1 upstream. Update the build rules to reflect that.
=> GHA: update curl version

.github/workflows/swift-toolchain.yml
Split out the standard library build phase to allow us to build the macros for the correct hosts. This is required to allow us to build the macros for distribution and for the build of the SDK.
=> GHA: split out standard library phase

.github/workflows/swift-toolchain.yml
Migrate from actions to `gh` to create the release to avoid some warnings. This also ensures that we no longer accidentally mark the 5.10 releases as the latest.
=> GHA: use `gh` to create release

.github/workflows/swift-toolchain.yml
These are not consumed by any other job or step.
In addition, this parameterizes the SQLite version, simplifying future updates.
=> [sqlite] Remove Android builds

.github/workflows/swift-toolchain.yml
Upstream now builds and packages the swift macros unconditionally. Update the build rules to do the same.
=> GHA: build Foundation Macros

.github/workflows/swift-toolchain.yml
`windows_build_runner` is too Windows-specific. This renames the variable to `default_build_runner`, to make space for future Darwin builds.
The variable is kept to its original name in the `context` step, since this step will eventually also output Darwin variables.
=> [Mac build] Rename builder to a generic name

.github/workflows/build-toolchain.yml, .github/workflows/swift-toolchain.yml
This is a preliminary step to eventually add the Mac build. The Mac build will be using a separate job with its own matrix.
=> [Mac build] Move build to sub-workflow

.github/workflows/swift-toolchain.yml
Now that the just built clang should no longer perform HCS on scoped EH functions, we should be able to enable this optimization globally.
=> GHA: enable HCS on Windows toolchains

.github/workflows/swift-toolchain.yml
Update the repositories which have migrated to the swiftlang organisation.
=> GHA: update repositories for swiftlang migration

.github/workflows/swift-toolchain.yml
We now need to download the standard library and the SDK to get the same content that we used to previously have in just the SDK. Adjust that accordingly.
=> GHA: repair the Windows runtime/SDK packaging

.github/workflows/swift-toolchain.yml
We are already building the Foundation macros but did not pass that along to the Foundation build. This is now required and failure to pass it along results in a build failure. Wire it up so that we can build and avoid another build of the macros.
=> GHA: wire up Foundation macros to swift-corelibs-foundation

.github/workflows/build-toolchain.yml, .github/workflows/swift-toolchain.yml
Introduce a build of swift-testing in the SDK as that is now distributed as part of the SDKs upstream. This allows us to have parity with the official builds.
=> GHA: setup builds for swift-testing

.github/workflows/swift-toolchain.yml
Depending on the runner configuration, `github.workspace` might be set up differently, resulting in issues when restoring previous builds from sccache. In order to work around this issue, this adds a hash of `github.workspace` to the sccache key to uniquely identify the build between different runner types.
=> Add the workspace hash to ccache key

.github/workflows/build-toolchain.yml
This was removed in #801 to bring the file in line with downstream. However, it is better to rely on the vars environment when invoking the main workflow from dispatch, while offering an override when invoking the workflow as a sub-workflow.
=> Use runners from vars if available

.github/workflows/swift-toolchain.yml
Fix the build failures in the devtools stage
=> fix devtools stage

.github/workflows/build-toolchain.yml, .github/workflows/swift-toolchain.yml
This adds a new Mac workflow, currently disabled by default and adapts the sqlite job to build on Mac. All other jobs are currently only enabled for Windows, they will be adapted in subsequent PRs.
=> [Mac build] Add optional Mac build

.github/workflows/swift-toolchain.yml
The "macros" jobs are configured to only build shared libraries.
=> [Macros] Remove upload exe step

.github/workflows/build-toolchain.yml, .github/workflows/swift-toolchain.yml
These were previously set to string types, resulting in incorrect
evaluation in `if` blocks.
=> Set boolean variables to boolean types

.github/workflows/build-toolchain.yml, .github/workflows/swift-toolchain.yml
Builds all 4 Android variants of compnerd/ds2 to be included in the Android SDK.
NOTE: ds2 is not yet referenced by `swift/swift-installer-scripts`, so this change does not have any effect other than validating the build.
Manually inspected artifacts produced by the Android ds2 steps:
```
C:\Users\Andrew\Downloads>unzip -l ds2-Android-arm64.zip
Archive:  ds2-Android-arm64.zip
Length     EAs   ACLs    Date   Time    Name
--------    ---   ----    ----   ----    ----
11907472      0      0  08/24/24 17:31   bin/ds2
--------  -----  -----                   -------
11907472      0      0                   1 file
C:\Users\Andrew\Downloads>unzip -l ds2-Android-armv7.zip
Archive:  ds2-Android-armv7.zip
Length     EAs   ACLs    Date   Time    Name
--------    ---   ----    ----   ----    ---- …
```
=> [android] include ds2 as part of the Android SDK

.github/workflows/build-toolchain.yml, .github/workflows/swift-toolchain.yml
* Make zlib version an input so it only needs to be set once.
* Add matrix for Windows and Darwin targets. For now, Darwin does not build Android targets.
=> [Mac build] Add zlib to the Mac build

.github/workflows/swift-toolchain.yml
Include the Android ds2 binaries in the Swift toolchain Windows installer.
* Explicitly sets `ANDROID_INCLUDE_DS2=true` when building the installer so the ds2 Android binaries get included in the installer.
* Remove an extra "Android" from the download path to match the expected file location in the .wxs file.
Successful swift-toolchain build with this change [here](https://github.com/thebrowsercompany/swift-build/actions/runs/10744313759).
Downloaded the Android SDK installer artifacts `sdk-android-armv7-msi`, `sdk-android-x86_64-msi`, `sdk-android-arm64-msi`, and `sdk-android-i686-msi` and verified the `ds2` binary is present using Windows MSI viewer.
=> [android] include ds2 binary in the Android installer

.github/workflows/build-toolchain.yml
The variable had been erroneously names `ccflags`.
=> Set cflags matrix variable properly

.github/workflows/build-toolchain.yml, .github/workflows/swift-toolchain.yml
This is a required preliminary step to build the compiler on macOS.
* Separate Swift flags between Windows and Darwin.
* Move arch-specific and OS-specific flags to matrix.extra_flags.
=> [mac build] Build early swift-driver

.github/workflows/swift-toolchain.yml
Previously, the cmark-gfm libraries would be copied to the compilers binary directory in every job using the compilers. Since this is needed to run the compilers, this moves the cmark-gfm copy library step to be done once in the compilers job.
=> Copy cmark-gfm libraries in the compilers job

.github/workflows/build-toolchain.yml
Update to the latest build of ds2 which contains a number of fixes to improve Android and Linux debugging with lldb:
compnerd/ds2#173
compnerd/ds2#168
compnerd/ds2#166
compnerd/ds2#143
compnerd/ds2#149
compnerd/ds2@21ba9e31ac1863859d19bea1c7193ee951086d6b
compnerd/ds2#146
compnerd/ds2@7a03bbcda87e85c8bb67974c33890e2710539c24
compnerd/ds2#141
compnerd/ds2@67e77f192d52592f695757f0e913c684b3b1550f
compnerd/ds2@0cf4f7498ed84e321c5b4f77be2aa190385add15
compnerd/ds2@6c269217da706efc3db9c6e04245c62dc4d35ac8
compnerd/ds2@c6617e5f26182c3352581f8bb510ae1ed80677ad
compnerd/ds2@a55e03ab6a9330a1ef62f97afdb83ba25f4dfc3b
compnerd/ds2@3a083371038e2f871d02e946d773f2cf6533ecac
=> [ds2] update ds2 revision to nightly-2024-11-07

default.xml
It should be `release/6.0` as opposed to `main` as per https://github.com/swiftlang/swift/blob/555c00a7317764f8fa2e587af4f0f9f68df7a178/utils/update_checkout/update-checkout-config.json#L195 and https://github.com/swiftlang/swift/pull/76026
=> Fix the swift-testing branch in release/6.0

.github/workflows/swift-toolchain.yml
Remove the use of the `DEVTOOLS_ROOT` property when building the installer MSIs. References to this have been removed from the WiX projects as of swiftlang/swift-installer-scripts#347.
=> GHA: remove `DEVTOOLS_ROOT` property

.github/workflows/swift-toolchain.yml
* Refer to specific commit hashes rather than a branch like main for dependent actions.
=> Use commit hash for dependent actions

.github/workflows/swift-toolchain.yml
This switches to CMake to build swift-inspect, allowing it to cross-compile, and then package.
=> GHA: switch to CMake to build swift-inspect

.github/workflows/swift-toolchain.yml
Swift does not have a stable ABI. We need to ensure that the toolchain that is used in different phases is identical. Hoist the toolchain version definition to global state.
=> GHA: share the pinned toolchain definition

.github/workflows/swift-toolchain.yml
This wires up the early swift driver build even though this path does not yet work on Windows. This is preliminary support that is waiting on the last changes to enable the early swift driver on Windows.
=> GHA: enable early swift driver builds on Windows

.github/workflows/swift-toolchain.yml
libxml2 was added as a required dependency downstream in swiftlang/swift#77862. This brings in the libxml2 build to the compilers job to fix the build.
=> [compilers] Add libxml2 to the compilers job

.github/workflows/swift-toolchain.yml
Use the CMake CONFIG definitions to wire up LibXml2 rather than trying to manually add the dependencies.
=> GHA: adjust CMake invocation for libxml2 usage

.github/workflows/swift-toolchain.yml
This fixes an issue where the GHA upload/download tar artifact actions were using the first `tar` command in `PATH`, which may be a GNU tar command on Windows. GNU tar cannot properly parse Windows paths.
=> [GHA] Update GHA upload/download tar actions

.github/workflows/swift-toolchain.yml
* Do not attempt NuGet registration
This is now failing as NuGet is registered:
```
Register-PackageSource: D:\r\_work\_temp\c04a7ca5-aa41-491b-b9ad-0e09fb799d0c.ps1:4
Line |
4 |      Register-PackageSource -Name NuGet -Location https://www.nuget.or …
|      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| Package Source 'NuGet' exists.
```
https://github.com/thebrowsercompany/swift-build/actions/runs/11656344808/job/32454421580 (cherry picked from commit e2e1a79848ae6287244431e613d9121ed16a28a4)
=> Partial cherry-pick: Fixes to get main working downstream again (#841)

.github/workflows/swift-toolchain.yml
This an attempt to fix the sccache error
```
sccache: error: failed to execute compile
sccache: caused by: cannot find binary path
```
https://github.com/thebrowsercompany/swift-build/actions/runs/12226735048/job/34102700092
=> Update and pin the sccache version following main and release/6.0

.github/workflows/build-toolchain.yml, .github/workflows/swift-toolchain.yml
- Introduce the concept of ARM64 CI runners. Use the cirun ARM64 machines as the ARM64 runners.
- Split the windows_build job into X64 and ARM64.
- Add the Win/ARM64 build on the Win/ARM64 runner (but no Win/X64 build on Win/ARM64 runner) while retaining the existing Win/X64 and Win/ARM64 builds on the Win/X64 runner.
- Split some of strategy matrices between X64 and ARM64.
- Append the "... (building on <os> <arch>)" to the job names to clarify what's building on what runner.
- Do not release the natively-released Win/ARM64 installer.exe while retaining the existing cross-compiled Win/ARM64 and Win/X64 installer.exe as the published release.
- Exclude the Android-related components including ds2 in the native Win/ARM64 build due to the non-existence of the native Windows/ARM64 Android …
=> Add the native ARM64 toolchain build to the main CI

.github/workflows/swift-toolchain.yml
The condition for building Foundation in the SDK job was erroneously set to build when the Android build was disabled.
=> [sdk] Skip Foundation build if Android is skipped

.github/workflows/swift-toolchain.yml
The SDK MSI filename for the Windows builds is now
`sdk.windows.${arch}.msi`. Similarly, the SDK MSI filename for
Android is now `sdk.android.${arch}.msi`.
In addition, the `rtl.${arch}.msm` does not have a corresponding
`.cab` file so it has been removed.
=> [Packaging] Update the SDK MSI filename

.github/workflows/swift-toolchain.yml
This updates the upload and download actions to use the tar-artifact actions for the compilers and cmark-gfm artifacts, paving the way for the Mac compilers build.
=> [Mac build] Update upload/download actions

.github/workflows/build-toolchain.yml
These were erroneously set up on the Windows build matrix, when they should have been set for the Windows host matrix.
=> [matrix] Set cmake_linker_flags for Windows hosts

.github/workflows/build-toolchain.yml
This makes the options more similar by providing a description rather than relying on the user to know what the input variable is meant for.
=> GHA: add a description for `build_android` input

.github/workflows/swift-toolchain.yml
The `sdk.wixproj` files were moved upstream.
=> [wix] Use updated paths for `sdk.wixproj`

.github/workflows/swift-toolchain.yml
Installing the latest Python 3.9 version proved to be an issue on some bot configuration. This reverts to installing 3.9.10 for Windows, which should solve the issue.
=> [compilers] Separate Windows/Mac python versions

.github/workflows/build-toolchain.yml, .github/workflows/swift-toolchain.yml
swift-lmdb is now a required dependency of IndexStoreDB.
=> [devtools] Add swift-lmdb to the devtools job

.github/workflows/swift-toolchain.yml
https://github.com/thebrowsercompany/swift-build/releases/tag/swift-6.0.0-20241216.0
which has the arm64 compiler fixes.
=> Update the windows pinned toolchain to bcny swift-6.0.0-20241216.0

.github/workflows/swift-toolchain.yml
Add a new `smoke-test-android` job to the `swift-toolchain` GitHub workflow that builds a Swift project for Android against the newly produced Android SDK. This job validates the newly build SDK can successfully build a small Swift project for Android before it is released.
* Adds a new `smode_test_android` job runs on Windows
* Limit the new job to run only when the Android SDK is built as part of the overall workflow
* Downloads and installs the SDK artifact built in previous steps
* Uses a custom install step copy+pasted from the existing Windows `smoke_test` job; it doesn't look like `compnerd/gha-setup-swift` can install using a local installer file yet
* Installs the Android NDK
* Checks-out and builds the [cassowary project](https://github.com/compnerd/cassowary) v0.0.2 for Android …
=> [android] add smoke_test_android job to validate Android SDK

.github/workflows/build-toolchain.yml, .github/workflows/swift-toolchain.yml
This is no longer used as a dependency for swift-driver, remove the unnecessary build.
=> GHA: remove Yams from the build

.github/workflows/swift-toolchain.yml
In swiftlang/swift-installer-scripts#358, the ProductArchitecture value for packaging the Android SDK was changed.
=> [packaging] Update value for ProductArchitecture

.github/workflows/swift-toolchain.yml
Currently, in the `stdlib` job, the toolchain is extracted to `BuildRoot/Library`, and the Swift Standard Library is also installed to `BuildRoot/Library`. Other jobs typically extract the toolchain to `BinaryCache/Library`. This changes the extraction path to `BinaryCache/Library` in the `stdlib` job, bringing it in-line with the rest of the build.
In addition, this changes the Swift Standard Library artifact root to be `BuildRoot/Library`, rather than the full path to the platform SDK, `BuildRoot/Library/Developer/Platforms/${{ matrix.os }}.platform`. This is in preparation for adapting the job to build for macOS, where the Swift Standard Library will be installed under `Library/Toolchains/unknown-Asserts-development.xctoolchain/usr`.
Extracted from #843
=> [stdlib] Change paths for stdlib job and artifacts

.github/workflows/build-toolchain.yml, .github/workflows/swift-toolchain.yml
Track the revision of swift-build. This is not yet wired up into the build, but this is the first step towards integrating swift-build into the toolchain.
=> GHA: wire up swift-build revision tracking

.github/workflows/build-toolchain.yml, .github/workflows/swift-toolchain.yml
This was changed upstream to use `lib` prefix for static libraries on Windows for Swift. Apply the necessary build changes to ensure that the build system is aware of this.
=> GHA: tweak the library naming for static libraries

.github/workflows/swift-toolchain.yml
* Add the global `cmake_linker_flags` when configuring build for `swift-certificates` and `SourceKit-LSP`. This implicitly adds `CMAKE_STATIC_LIBRARY_PREFIX_Swift="lib"` as needed on Windows.
* Move position of `-D CMAKE_STATIC_LIBRARY_PREFIX_Swift=` later in the CMake configure command for `Compilers` so that it overrides the value pulled in by including the global `cmake_linker_flags`.
Ran Development Snapshot CI: https://github.com/thebrowsercompany/swift-build/actions/runs/13266881748
=> [gha] fix the Windows Swift toolchain build

.github/workflows/swift-toolchain.yml
With the removal of the runtimes build in unified build, we are able to universally inline some of the computation of the flags. Other options are no longer required to be evaluated at build time. Re-order some of the options to similarly order the macOS and Windows builds.
=> GHA: simplify the compiler context

.github/workflows/build-toolchain.yml
Reduce the size of the Swift Android SDK by using `-g split-dwarf` when building with debug symbols enabled.
Successful CI run with Android & debug symbols: https://github.com/thebrowsercompany/swift-build/actions/runs/13395138729
Observed size reduction of Android installer by 7-8 MB per architecture:
* `sdk-android-arm64-msi`: 52.7 MB -> 46.1 MB
* `sdk-android-armv7-msi`: 53.2 MB -> 46.8 MB
* `sdk-android-i686-msi`: 53.4 MB -> 47.2 MB
* `sdk-android-x86_64-msi`: 53 MB -> 46.4 MB
=> [android] link Android components with `-g split-dwarf` to reduce size

.github/workflows/swift-toolchain.yml
Made to be consistent with what we do in do in build.ps1 - use Swift\Toolchains\0.0.0+Asserts: this is the debug build, so use Asserts (not noAsserts)
This is one of 3 changes required. See PR for discussion with @compnerd 
Find the PR originally filed at:
https://github.com/thebrowsercompany/swift-build/pull/251 
Find the original issue at
https://github.com/thebrowsercompany/swift-build/issues/248
=> rewords toolchain -development to 0.0.0

.github/workflows/build-toolchain.yml, .github/workflows/swift-toolchain.yml
* Adapt stdlib job to build for both Windows and Mac.
=> [Mac Build] Add stdlib build

.github/workflows/swift-toolchain.yml
This is required for the Mac build. This also renames the "os-stdlib-arch" artifact to "stdlib-os-arch" for consistency for other artifacts.
=> Use GHA upload/download tar actions for stdlib

.github/workflows/swift-toolchain.yml
This speeds up the no-Android builds by disabling unneeded downloads and repo syncs.
=> Skip more steps if Android is disabled

.github/workflows/build-toolchain.yml, .github/workflows/swift-toolchain.yml
This moves all artifacts for a single os/arch combo together in the GitHub Actions page, making it easier to download relevant artifacts when reproducing a build.
=> Rename artifacts to use os-arch-name pattern

.github/workflows/build-toolchain.yml
Enable building with a custom fork of the repo manifest enabling patched forks to be used as the source of a build.
=> GHA: allow overriding the repo manifest

.github/workflows/swift-toolchain.yml
Adjust the install fixup to remove the re-organisation as XCTest will install a thick module by default.
=> GHA: XCTest now installs a thick module

.github/workflows/swift-toolchain.yml
The installer rules are progressively assuming a fully staged toolchain. We did not previously shuffle the C headers that Foundation expects into the correct location. Do so to allow packaging with the updated manifest.
=> GHA: shuffle the Foundation headers

.github/workflows/swift-toolchain.yml
These should now be versioned to the product version as per upstream. Adjust the installation accordingly.
=> GHA: adjust testing framework install locations

.github/workflows/swift-toolchain.yml
Bring this in line with the build.ps1 equivalent, removing the file shuffling post-installation.
=> GHA: adjust the XCTest and Testing CMake invocations

.github/workflows/build-toolchain.yml, .github/workflows/swift-toolchain.yml
Add `variant` to the compilers matrix and update downstream steps.
=> variants: Build Asserts and NoAsserts compilers.

.github/workflows/swift-toolchain.yml
This is now properly normalised to the expected triple (armv7-unknown-linux-android). Account for this in the build so that we don't have to shuffle files for the installer packaging.
=> GHA: adjust the ds2 prefix for Android ARMv7

.github/actions/setup-sccache/action.yml, .github/workflows/swift-toolchain.yml
This wraps our usage of sccache in a custom action that will configure either direct usage, or s3 usage based on whether or not you've passed in an AWS ARN that can be used to authenticate to an S3 bucket when setting up sccache.
A side effect of this is that we will have to checkout the `swift-build` repo in order to gain access to the action that we're authoring.
=> Add custom sccache setup action

.github/actions/setup-sccache/action.yml, .github/workflows/build-toolchain.yml, .github/workflows/swift-toolchain.yml
We want to dynamically upgrade the sccache configuration if S3 access via SSO is setup. To do this while preserving backward disk caching compatibility we specify 3 new environment variables:
- `SCCACHE_S3_BUCKET`
- `SCCACHE_AWS_REGION `
- `SCCACHE_AWS_ARN `
If the `SCCACHE_AWS_ARN` is set the sccache action will attempt to validate that the other two values are not null or an empty string before pushing them into the environment for sccache to pick up.
We have to also specify `id-token: write` permissions at the top level entry points into the CI process since github tokens cannot be upgraded when workflows get called (they can only get downgraded) so we have to put the complete set of permissions at the root of CI.
=> Add dynamic configuration of sccache based on available environment variables

.github/workflows/swift-toolchain.yml
`vfs-overlay.yaml` created as part of the `stdlib` step refers to paths from the `swift` source directory, which may not be available in subsequent jobs, causing build issues. These changes generate a `vfs-overlay.yaml` file on demand for jobs that need it, to work around the issue.
=> Create vfs-overlay.yaml on demand

.github/actions/setup-sccache/action.yml
It seems like there is some eagerness with GitHub actiosn starting to run steps after a previous step is not totally complete or some issue with ensuring those env variables are set correctlly across steps. This forces us to wait until after we've successfully assumed the credentials role to configure the cache.
=> Setup remote cache after auth success

.github/actions/setup-sccache/action.yml
We should only setup the local cache when the arn is missing for s3 usage. Otherwise we will try to spawn two different configurations of sccache.
=> Only setup local cache when arn is missing

.github/workflows/swift-toolchain.yml
We do a small bit of C/C++ building in the SDK job which could benefit from also using sccache. This sets the cache up with the associated steps for fallback to disk cache and workspace hash computation.
=> Setup sccache for SDK job

.github/workflows/swift-toolchain.yml
`Move-Item` moves items to a file if the destination does not exist. In addition, this fixes the platform value for the Package Windows SDK job.
=> Create directory before moving items

.github/workflows/swift-toolchain.yml
Enable caching for the NDK when installing to speed up subsequent installations. This is important as the Android NDK installation takes ~6x longer than the longest step for jobs such as zlib.
=> GHA: enable caching of the NDK

.github/workflows/swift-toolchain.yml
Update the installer build phase for the new packaging setup. This merges the various Windows builds and android builds into one per platform irrespective of the architectures.
=> GHA: adjust the installer build phases

.github/workflows/swift-toolchain.yml
This fixes the Windows Arm64 build job.
=> Packaging: Set `productArchitecture`

.github/workflows/swift-toolchain.yml
`if (true)` is not valid PowerShell. This updates the test to properly include the Android platform if needed.
=> Installer: Properly include Android platform

.github/workflows/swift-toolchain.yml
This is no longer required with mimalloc 3.0.3.
=> mimalloc: Remove workaround for mimalloc

.github/actions/setup-sccache/action.yml
These changes attempt to address the intermittent failure we are seeing during the sccache initialization.
1. Switch to use `thebrowsercompany/ccache-action` instead of `hendrikmuhs/ccache-action`.  
The only difference is updating to a newer version of sccache (`v0.10.0` instead of `v0.7.6`).  
The changes between the two are pushed to a PR (Update sccache version to v0.10.0: hendrikmuhs/ccache-action#315). Once merged, we can revert back to the upstream release.  
2. Update `configure-aws-credentials` to the latest version.  
This update uses the `special-characters-workaround` flag that was introduced last year.  
The flag seems to address the issue we are running into. The action will now check if the AWS secrets have any special characters ("+" or "/" among others), and if so, it …
=> Update configure-aws-credentials and ccache-action

.github/workflows/build-toolchain.yml, .github/workflows/swift-toolchain.yml
This updates the packaging steps following swiftlang/swift-installer-scripts#413
This cherry-picks the following PRs:
* GHA: shuffle the Foundation headers #918
* GHA: shuffle more files for Dispatch, Foundation #935
* Create directory before moving items #936
* GHA: adjust the installer build phases #937
* GHA: enable _Builtin_float on android #942
* Installer: Properly include Android platform #944
* Update Android root folder #943
* Packaging: Set productArchitecture #941
* Android: Update Android platform packaging #940
=> GHA: Update packaging

.github/actions/setup-sccache/action.yml
Now that we have an official release of `ccache-action` switch to it: https://github.com/hendrikmuhs/ccache-action/releases/tag/v1.2.18
=> Update ccache-action to v1.2.18

.github/workflows/swift-toolchain.yml
SourceKit-LSP gained a new dependency on ASN1, update the workflow to accommodate that in the CMake invocation.
=> GHA: adjust build invocation for SourceKit-LSP

.github/workflows/swift-toolchain.yml
Prepare to build swift-build in the toolchain build as it is about to the packaged up into the installer.
=> GHA: add swift-build to the build

.github/workflows/swift-toolchain.yml
This matches upstream `build.ps1` behavior.
=> Switch swift-system to build statically

.github/workflows/swift-toolchain.yml, default.xml
Cherry-pick https://github.com/compnerd/swift-build/pull/945 into release/6.2
This is no longer required with mimalloc 3.0.3.
=> [Cherry-pick] mimalloc: Remove workaround for mimalloc

.github/workflows/swift-toolchain.yml
Cherry-picked from #955
This matches upstream `build.ps1` behavior.
=> [6.2] Switch swift-system to build statically

.github/workflows/swift-toolchain.yml
Cherry-picked from #954
Prepare to build swift-build in the toolchain build as it is about to the packaged up into the installer.
=> [6.2] GHA: add swift-build to the build

.github/actions/setup-build/action.yml, .github/workflows/test-setup-build.yml
This introduces a new reusable action, `setup-build`, which will eventually replace all of the custom installation steps in the swift-build jobs. Currently it only supports providing explicit versions for MSVC and the Windows SDK.
This also adds tests for the `setup-build` action, with a configurable runner, ensuring we can catch issues early as runner images get updated.
Bug: #821
=> Add reusable action for MSVC + Win SDK overrides

.github/workflows/swift-toolchain.yml
The artifact name had been incorrectly set to `Windows-${{ inputs.build_os}}`, which expands to `Windows-Windows`.
=> ds2_tools: Use `build_arch` for the artifact name

.github/actions/setup-build/action.yml, .github/workflows/test-setup-build.yml
Rather than dumping the log to the bot output, the log file is now uploaded as an artifact named after the job name.
=> Upload the VS Installer log

.github/workflows/test-setup-build.yml
The back ticks were meant to escape quotes, not the dollar sign.
=> test-setup-build: Properly escape quotes

.github/workflows/swift-toolchain.yml
* Use the `setup-build` action in every job.
* Move the build machine setup to the beginning of the job as this saves time when it fails.
* Remove `WORKAROUND_WINDOWS_SDK_VERSION` for the smoke tests, they should test the latest Windows SDK version.
=> build: Use the setup-build action in swift-toolchain

.github/workflows/build-toolchain.yml, .github/workflows/swift-toolchain.yml
Start attesting the installer artifacts. While we can attest the build further, this allows the user consumable artifacts to be attested. The binaries themselves should be attested as well but code signing the installer should allow us to validate the binaries.
=> GHA: add attestation for the installer artifacts

.github/workflows/swift-toolchain.yml
This embeds a compiler version tag into the output so that we can easily identify the toolchain.
=> GHA: setup swift toolchain version information

.github/actions/setup-build/action.yml
As suggested on the [DevComm](https://developercommunity.visualstudio.com/t/Visual-Studio-Installer-randomly-fails-t/10924708?) thread, this adds `--noUpdateInstaller` to the `vs_installer.exe` invocation to disable the installer self-update.
This solves the issue of `vs_installer.exe` silently failing to install the requested packages.
=> setup-build: Disable `vs_installer.exe` self-update

.github/actions/setup-build/action.yml, .github/workflows/swift-toolchain.yml, .github/workflows/test-setup-build.yml
* Add support for both upstream and BCNY Swift toolchain installation as part of the `setup-build` action.
* Update users of the `gha-setup-swift` action.
=> setup-build: Support Swift toolchain installation

.github/actions/setup-build/action.yml, .github/workflows/swift-toolchain.yml
* Following installation of the bootstrap toolchain, this adds a step to update the installed module maps for their upstream versions, which are compatible with the latest Windows SDKs.
* As a result, remove the workaround Windows SDK version.
=> Overwrite the bootstrap Swift toolchain module maps

.github/workflows/swift-toolchain.yml
A temprorary fix to allow CI to make progress until  https://github.com/swiftlang/llvm-project/pull/10949 lands
Here is a downstream run: https://github.com/thebrowsercompany/swift-build/actions/runs/16124908464
=> Escape input to LLVM_EXTERNAL_SWIFT_SOURCE_DIR

.github/workflows/swift-toolchain.yml
The bootstrap toolchain is being updated upstream in swiftlang/swift#82914.
This also removes all of the remaining workarounds required for the 6.0 toolchain.
=> Update boostrap toolchain to 6.1.2

.github/workflows/build-toolchain.yml, .github/workflows/swift-toolchain.yml
Prepare for building swift-subprocess, start tracking the revision information.
=> GHA: add swift-subprocess revision tracking

.github/actions/setup-build/action.yml, .github/workflows/test-setup-build.yml
Due to a bug in the VS installer self-update process, it sometimes fails to properly self-update, preventing the installation of the MSVC packages that we need.
In order to work around this issue, we download the newest VS installer for the installed product and run its update process before installing the MSVC packages.
=> setup-build: Update VS Installer

.github/workflows/build-toolchain.yml, .github/workflows/swift-toolchain.yml, default.xml
This also modifies the build order to use the same build of ASN1 for swift-crypto rather than vendoring it automatically for the swift-crypto build.
=> Update swift-crypto to 3.12.5

.github/workflows/build-toolchain.yml, .github/workflows/swift-toolchain.yml
Follow up on to https://github.com/compnerd/swift-build/pull/983. This changes adds a new var to control the version of Python used in the execution of CI actions (not the version used to build lldb).
This also fixes an break introduced in the same PR on ARM64 machines by forcing the use of `x64` emulated version. 
Downstream runs:
AMD: https://github.com/thebrowsercompany/swift-build/actions/runs/16863879408
ARM: https://github.com/thebrowsercompany/swift-build/actions/runs/16863881987
=> Use a variable to control the version of python used in ci actions

.github/workflows/swift-toolchain.yml
Fix build break for missing CxxStdlib in experimental runtime build 
Changes
- Add missing `SwiftCore_ENABLE_REMOTE_MIRROR` to core
- Add missing `SwiftOverlay_ENABLE_CXX_INTEROP` to overlay
- Remove all swiftFlags from all targets
Downstream successful job: https://github.com/thebrowsercompany/swift-build/actions/runs/17053239286
=> Upstream experimental overlay fix

.github/actions/configure-cmake-project/action.yml, .github/workflows/swift-toolchain.yml
Convert `experimental-sdk` job to use `configure-cmake-project`. Also fix a typo in the action when handling `use-gnu-driver` option
Successful downstream job: https://github.com/thebrowsercompany/swift-build/actions/runs/17390839011
=> Build: use configure-cmake-project action in experimental-sdk job

.github/workflows/swift-toolchain.yml
My change introduced a break on cirun machines for missing pinned compilers. so this change uses the built-compilers which seems to do the trick.
downstream job: https://github.com/thebrowsercompany/swift-build/actions/runs/17500660240/job/49716449757?pr=311
=> Use built compilers since we are not isntalling pinned toolchain for this job

.github/workflows/swift-toolchain.yml
Convert `dev-tools` job to use `configure-cmake-project`
Successful downstream job: https://github.com/thebrowsercompany/swift-build/actions/runs/17351551308
=> Build: use configure-cmake-project action in dev-tools job

.github/workflows/swift-toolchain.yml
Convert `debugging_tools` job to use `configure-cmake-project`. Also fix a typo in the action when handling `use-gnu-driver` option
Successful downstream job: https://github.com/thebrowsercompany/swift-build/actions/runs/17417472433
=> Build: use configure-cmake-project action in debugging_tools job

.github/workflows/build-toolchain.yml, .github/workflows/swift-toolchain.yml
This changes builds the online flavor of the installer and uploads the binaries to a public R2 storage bucket. The offline installer is still available. 
- Build both online and offline installer
- upload cabs and msi files to R2 storage and use the url to build the installer
- Use the online installer for smoke testing
- Change name of payloads accordingly
- testing the resulting installer localy
- smoke testing with the new installer
**Successful downstream job (https://github.com/thebrowsercompany/swift-build/actions/runs/17561511426) ** (Note: i still need to test changes to upload files on the release)
=> Build online installer

.github/workflows/swift-toolchain.yml
This change
- Saves the names of all .dlls in the runtime's `/usr/bin` for all architectures
- For all experimental SDK rtl MSMs:
- If shared, checks that all .dlls from the runtime are present
- If static, checks that all .dlls on a hardcoded list are present
=> Add smoke tests to ensure redistributables have expected DLLs

.github/workflows/build-toolchain.yml, .github/workflows/swift-toolchain.yml
Upcoming change: https://github.com/swiftlang/swift/pull/83441
=> Build Brotli in advance of it being a Foundation dep

.github/workflows/swift-toolchain.yml
Add a new smoke test for https://github.com/pointfreeco/swift-issue-reporting. 
This caught the issue in https://github.com/swiftlang/swift-installer-scripts/pull/469
Passing downstream run: https://github.com/thebrowsercompany/swift-build/actions/runs/18328968588/job/52208026579
=> Add new smoke test for swift-issue-reporting
