compnerd/swift-build

docs/Windows.md

See https://forums.swift.org/t/re-foundation-on-windows-ci-nightlies/27993/35. Quite detailed, too much? What I did not fully understand: For what builds should I search for for to get the right ones, one build with "facebook" did not work as indented.

more detailed instructions for installing on Windows

---

.ci/azure-pipelines-aws-agent.yml

Try to build the stdlib/sdk overlay here

Update azure-pipelines-aws-agent.yml for Azure Pipelines

---

docker/Ubuntu-18.04/Dockerfile

Use the new apt repository to install the swift content.  Split out some
of the commands into layers which can be run individually since they
add content which is preserved.

docker: use ubuntu repository

---

.ci/linux-sdk.yml
.ci/templates/curl.yml
.ci/templates/linux-sdk.yml
.ci/templates/windows-sdk.yml
.ci/templates/zlib.yml

- use BinariesDirectory for build
- use SourcesDirectory for sources
- use PublishPipelineArtifacts

zlib, curl: improvements

---

.ci/linux-devtools.yml
.ci/templates/linux-devtools.yml
.ci/templates/sqlite3.yml
.ci/templates/windows-devtools.yml

- use BinariesDirectory for build
- use SourcesDirectory for sources
- use PublishPipelineArtifacts to publish
- use DownloadPipelineArtifacts to consume

sqlite: improvements

---

.ci/templates/windows-sdk.yml
.ci/windows-sdk-5.2.yml
.ci/windows-sdk-facebook-vs2017.yml
.ci/windows-sdk-facebook-vs2019.yml
.ci/windows-sdk.yml

Use the checkout task to do multi-repository checkouts

windows: convert checkout to checkout task

---

.ci/templates/curl.yml

Hope it works same way as in sdk template where I got the path variable.

[CURL] correct zlib path

---

.ci/vs2019-swift-5.2.yml

Add an installer for the 5.2 release.

Installer: create installer for swift 5.2

---

wix/windows-runtime.wxs
wix/windows-toolchain.wxs

Reverts compnerd/swift-build#188

Revert "Use correct property name in PATH setter"

---

wix/windows-icu.wxs
wix/windows-runtime.wxs
wix/windows-tensorflow.wxs
wix/windows-toolchain.wxs

Adjust the path to include the volume name as pointed out by @wjk.

install: prefix paths with the volume

---

.ci/curl.yml
.ci/templates/curl.yml

This cleans up the curl template to be less dense and remove some
obsolete workarounds.

curl: clean up some readability

---

.ci/templates/macos-sdk.yml
.ci/templates/windows-sdk.yml

Flip the TensorFlow builds to x10.

TensorFlow: switch to X10

---

wix/windows-runtime.wxs
wix/windows-sdk.wxs
wix/windows-tensorflow.wxs

This updates the installers for Windows to install the X10 files now
that is being built.

WIX: install X10 files from tensorflow/swift-apis

---

cmake/ICU/CMakeLists.txt

This should repair the threading issue with `gencnvl`.

ICU: try to link against pthreads explicitly

---

README.md

Refine the first paragraph in README.md

---

.ci/templates/linux-devtools.yml

Add Yams to get s-p-m builds working again.

CI: add Yams to Linux devtools

---

.ci/icu.yml
.ci/templates/icu.yml
.ci/ubuntu-18.04-flowkey.yml
.ci/ubuntu-18.04-google.yml
.ci/vs2017-facebook.yml
.ci/vs2019-facebook.yml
.ci/vs2019-google.yml
.ci/vs2019-master-next.yml
.ci/vs2019-swift-5.2.yml
.ci/vs2019-tensorflow.yml
.ci/vs2019.yml
cmake/ICU/CMakeLists.txt

Update the ICU build to 67.1 experimentally.  If this actually repairs
the ICU build, it may be valuable to jump to it.

CI: attempt to update ICU to to 67.1

---

cmake/toolchains/android.toolchain.cmake

Update the toolchain definition from upstream.

toolchain: sync android.toolchain.cmake

---

swift-numerics.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/compnerd/swift-build/254)

Set up CI with Azure Pipelines

---

.ci/tensorflow.yml

Bump TensorFlow to 2.3.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/compnerd/swift-build/256)

Update tensorflow.yml for Azure Pipelines

---

.ci/templates/windows-devtools.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/compnerd/swift-build/260)

CI: add Yams to the windows devtools

---

.ci/templates/linux-devtools.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/compnerd/swift-build/262)

CI: repair the Linux devtools

---

.ci/templates/toolchain.yml
.ci/vs2019-swift-5.3.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/compnerd/swift-build/261)

toolchain: repair Windows ARM64 cross-compile

---

.ci/templates/windows-devtools.yml

[skip ci]
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/compnerd/swift-build/268)

CI: start installing devtools for Windows

---

.ci/macOS-tensorflow.yml
.ci/macOS.yml
.ci/ubuntu-18.04-flowkey.yml
.ci/ubuntu-18.04-google.yml
.ci/vs2017-facebook.yml
.ci/vs2017.yml
.ci/vs2019-devtools.yml
.ci/vs2019-facebook.yml
.ci/vs2019-google.yml
.ci/vs2019-master-next.yml
.ci/vs2019-swift-5.2.yml
.ci/vs2019-swift-5.3.yml
.ci/vs2019-tensorflow.yml
.ci/vs2019.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/compnerd/swift-build/269)

CI: checkout swift-argument-parser

---

.ci/templates/devtools-deb.yml
.ci/templates/icu-deb.yml
.ci/templates/icu-msi.yml
.ci/templates/linux-devtools.yml
.ci/templates/linux-sdk.yml
.ci/templates/sdk-deb.yml
.ci/templates/sdk-msi.yml
.ci/templates/swift-installer-bundle.yml
.ci/templates/tensorflow-msi.yml
.ci/templates/toolchain-deb.yml
.ci/templates/toolchain-msi.yml
.ci/templates/toolchain.yml
.ci/templates/windows-devtools.yml
.ci/templates/windows-sdk.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/compnerd/swift-build/270)

CI: add the swift-argument-parser to the checkout

---

.ci/templates/linux-devtools.yml
.ci/templates/windows-devtools.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/compnerd/swift-build/271)

CI: add swift-argument-parser to the devtools build

---

.ci/templates/windows-devtools.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/compnerd/swift-build/272)

devtools: attempt to adjust flags for self-hosting s-p-m

---

.ci/vs2019-devtools.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/compnerd/swift-build/273)

CI: add a scheduled build

---

.ci/templates/android-sdk.yml
.ci/templates/toolchain.yml
.ci/templates/windows-devtools.yml
.ci/templates/windows-sdk.yml
.ci/vs2017-swift-5.2.yml
.ci/vs2019-swift-5.2.yml
.ci/vs2019-swift-5.3.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/compnerd/swift-build/276)

CI: Use Python 3 instead of 2

---

.ci/templates/swift-installer-bundle.yml
.ci/vs2019-tensorflow.yml
.ci/vs2019.yml
wix/windows-bundle.wixproj
wix/windows-bundle.wxs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/compnerd/swift-build/280)

CI: package devtools in tensorflow builds

---

.ci/templates/windows-sdk.yml

These will communicate information to swift-package-manager.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/compnerd/swift-build/287)

CI: add a couple of plists

---

wix/windows-sdk.wxs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/compnerd/swift-build/288)

Installer updates

---

.ci/templates/sdk-msi.yml
wix/windows-sdk.wixproj
wix/windows-sdk.wxs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/compnerd/swift-build/291)

WIX: add files for new swiftmodule layout

---

wix/windows-sdk.wxs

This restructures the installed image to install the stdlib import
libraries into `usr/lib/swift` rather than `usr/lib/swift/windows`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/compnerd/swift-build/294)

WIX: hoist import libraries a level

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/compnerd/swift-build/301)

Add documentation for downloading the latest builds

---

.ci/templates/windows-devtools.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/compnerd/swift-build/299)

CI: add IndexStoreDB to devtools

---

wix/windows-devtools.wxs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/compnerd/swift-build/306)

WIX: package IndexStoreDB in devtools MSI

---

.ci/templates/windows-devtools.yml
.ci/vs2017.yml
.ci/vs2019-devtools.yml
.ci/vs2019-facebook.yml
.ci/vs2019-google.yml
wix/windows-devtools.wxs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/compnerd/swift-build/307)

CI: add SourceKit-LSP to devtools build on Windows

---

.ci/templates/sdk-msi.yml
wix/windows-runtime.wixproj
wix/windows-runtime.wxs
wix/windows-sdk.wixproj
wix/windows-sdk.wxs

The Windows SDK has replaced the MSVCRT module with CRT.  Update the
installer accordingly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/compnerd/swift-build/312)

WIX: msvcrt -> crt migration

---

.ci/templates/sdk-msi.yml

Adjust the TensorFlow builds as they haven't caught up to the MSVCRT ->
CRT transition.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/compnerd/swift-build/313)

SDK: tensorflow is a bit behind, account for that

---

.ci/templates/windows-sdk.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/compnerd/swift-build/315)

SDK: add extra swiftc flags for Windows

---

.ci/vs2019-tensorflow.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/compnerd/swift-build/318)

Update vs2019-tensorflow.yml with 0.12 tags

---

.ci/vs2019-tensorflow.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/compnerd/swift-build/319)

Revert name of Yams to jpsim

---

.ci/vs2019-tensorflow.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/compnerd/swift-build/320)

Update PythonKit sha

---

.ci/vs2019-tensorflow.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/compnerd/swift-build/321)

Update SHA for swift-argument-parser

---

.ci/templates/sdk-msi.yml

TensorFlow has caught up to the new layout, remove the TF specific case.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/compnerd/swift-build/322)

Cherry pick Update sdk-msi.yml

---

.ci/vs2019-tensorflow.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/compnerd/swift-build/323)

Bump TSC now that dev tags are published.

---

.ci/templates/sdk-msi.yml
wix/windows-runtime.wixproj
wix/windows-runtime.wxs
wix/windows-sdk.wixproj
wix/windows-sdk.wxs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/compnerd/swift-build/327)

wix: package `_Concurrency` for Windows

---

docs/Windows.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/compnerd/swift-build/330)

Update apple/swift links -> `main`

---

.ci/templates/sdk-msi.yml
wix/windows-runtime.wixproj
wix/windows-runtime.wxs
wix/windows-sdk.wixproj
wix/windows-sdk.wxs

Add the `_Differentiation` module to the installed image for Windows.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/compnerd/swift-build/333)

WIX: package _Differentiation module

---

wix/windows-sdk.wxs

Add the _Concurrency module import library.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/compnerd/swift-build/334)

WIX: include swift_Concurrency.lib

---

.ci/sqlite3.yml
.ci/templates/linux-devtools.yml
.ci/templates/sqlite3.yml
.ci/templates/windows-devtools.yml
.ci/vs2019-devtools.yml
.ci/vs2019-google.yml
.ci/vs2019-master-next.yml
.ci/vs2019-swift-5.3.yml
.ci/vs2019-swift-5.4.yml
.ci/vs2019.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/compnerd/swift-build/336)

SQLite3: bump to 3.34.0

---

.ci/templates/windows-devtools.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/compnerd/swift-build/344)

CI: build swift-crypto as part of devtools

---

.ci/templates/devtools-msi.yml
.ci/vs2019-swift-5.4.yml
wix/windows-devtools.wixproj
wix/windows-devtools.wxs

As SPM now links against SwiftCrypto, package it into the toolchain.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/compnerd/swift-build/347)

WIX: package swift-crypto for SPM

---

.ci/templates/swift-installer-bundle.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/compnerd/swift-build/348)

CI: correct the installer bundle package path

---

wix/SwiftInstaller/Headers/logging.hh
wix/SwiftInstaller/Headers/scoped_raii.hh
wix/SwiftInstaller/Headers/swift_installer.hh
wix/SwiftInstaller/Sources/DllMain.cc
wix/SwiftInstaller/Sources/logging.cc
wix/SwiftInstaller/Sources/swift_installer.cc
wix/SwiftInstaller/SwiftInstaller.vcxproj
wix/SwiftInstaller/SwiftInstaller.vcxproj.filters
wix/SwiftInstaller/ThirdParty/Microsoft.VisualStudio.Setup.Configuration.Native/inc/Setup.Configuration.h
wix/windows-sdk.wixproj
wix/windows-sdk.wxs

Add a custom action to manage the support files that are needed for
using Swift on Windows.

Installer: start sketching out a custom action

---

.github/workflows/swift-format.yml
wix/swift-format.wixproj
wix/swift-format.wxs

This packages up swift-format as a MSI to simplify deployment.

swift-format: package up into a MSI

---

.ci/templates/toolchain.yml

As we found from previous attempt, template parameters are not evaluated for conditions.
Now trying to pass Swift version through variables.

Use older CMake for 5.4 and newer CMake for other branches, attempt 2

---

.github/workflows/swift-toolchain.yml

Made this typo in #390, and since then it is an eyesore to me. Can't stand it anymore😅

NFC: Fix typo in toolchain config command

---

.ci/vs2022-swift-5.6.yml
.ci/vs2022-swift-5.7.yml
.ci/vs2022.yml

Let's see how vs2022 build check handles vs_installer step now. I can't run identical test on my branch, unfortunately.

vs2022, wait for VC components installer completion

---

.ci/vs2022.yml

- most jobs are disabled
- toolchain is downloaded (I hope so) from previous run
- older toolset for ICU job

Experimental ICU build with older VC toolset

---

build.ps1

This allows re-rooting the source cache root.

build script: make `SourceCache` a parameter

---

build.ps1

This avoids the use of `-vfsoverlay` with a pointer into the Swift build tree.  This should allow us to use the same technique during the build on the CI systems.

build: use the staged SDK for the build

---

build.ps1

Building `sdk-$arch.wxs` requires that we preserve XCTest's cmake install layout, so we need to manually consolidate it later.

build.ps1: Fix consolidate step for XCTest

---

build.ps1

Updates the consolidation step to write to folders mimicking Program Files native and WoW directories.

build.ps1: Consolidate the redist installation mimicking Program Files

---

build.ps1

build.ps1: Revert configurable ProductVersion lost in bad rebase

---

build.ps1

Adds an optional step to copy the artifacts (msi's and installer) to where the Apple CI will expect them.

build.ps1: Support staging artifacts as expected by the Apple CI

---

build.ps1

Creating a mock install under `S:\Program Files` and `S:\Library` is for local development and won't be needed by the Apple CI, so this adds `$SkipInstall` to avoid this step.
- Add support for `$SkipInstall`
- Rename `Consolidate-***Install` methods to `Install-***`
- Make the platform installation more atomic by moving its install step after SDK for all architectures are built. Previously the directory would be deleted early and would not be re-populated unless the SDK builds succeeded.

build.ps1: Add $SkipInstall and rename Consolidate- to Install-

---

build.ps1

Avoids errors like:
```
[221/224] Linking Swift shared library bin\Foundation.dll
FAILED: bin/Foundation.dll Sources/Foundation/CMakeFiles/Foundation.dir/AffineTransform.swift.obj Sources/Foundation/CMakeFiles/Foundation.dir/Array.swift.obj Sources/Foundation/CMakeFiles/Foundation.dir/AttributedString/AttributedString.swift.obj Sources/Foundation/CMakeFiles/Foundation.dir/AttributedString/AttributedStringAttribute.swift.obj Sources/Foundation/CMakeFiles/Foundation.dir/AttributedString/AttributedStringCodable.swift.obj Sources/Foundation/CMakeFiles/Foundation.dir/AttributedString/AttributedStringRunCoalescing.swift.obj Sources/Foundation/CMakeFiles/Foundation.dir/AttributedString/AttributedString+Locking.swift.obj Sources/Foundation/CMakeFiles/Foundation.dir/Boxing.swift.obj …
```

Unset SDKROOT to avoid collisions with system-wide installed modulemaps

---

build.ps1

Looks like this was already added when I added it previously.

Remove extra SWIFT_ENABLE_EXPERIMENTAL_CXX_INTEROP

---

.github/workflows/SwiftFormat.yml

Update the actions versions to reduce some of the deprecation messages.

GHA: update some action version

---

build.ps1

Now prints the full command line invocation and environment variables.

build.ps1: More details when a command invocation fails

---

.github/workflows/SwiftFormat.yml

Also tweak the swift versioin number in the release name.

Use softprops/action-gh-release in SwiftFormat.yml.

---

.github/workflows/swift-toolchain.yml

Also replace the hardcoded cpu/architecture names with references the matrix.

Add a strategy matrix to the swift_format job.

---

build.ps1

Correct msbuild invocation for MSIs.

build: adjust configuration rules for WiX packages

---

build.ps1

Disable the default build from emitting debug information.  This will speed up the build and reduce the output size.  This is particularly important for the Swift side which will emit a large amount of metadata into the final binaries which is not stripped.
This is intended to be the default build type for CI.  For local builds, developers may use `-BuildType RelWithDebInfo` to get debug information emitted.

build: disable debug information on release builds

---

build.ps1

This is part of the default toolchain distribution and needs to be built for packaging as well as development.  Add this to the build set.

build: add `swift-inspect` to the build

---

.github/workflows/swift-doc.yml

For repeatability and security

Pin seanmiddleditch/gha-setup-vsdevenv GitHub action version

---

.azure/vs2022.yml
.github/workflows/swift-toolchain.yml
build.ps1

Accounts for changes in https://github.com/apple/swift-installer-scripts/pull/217

Fix paths to runtime wixproj file

---

.github/workflows/swift-toolchain.yml

So forks of this repo can use different-sized runner machines.

Support configuring runners through repo variables.

---

build.ps1

Another victim of tla-ization.

Fix reference to the runtime msi

---

.azure/vs2022-swift-5.9.yml

AzDO, 5.9: truncate intermediate output files to save space

---

build.ps1

Adjust the flags to be passed along even if we are not using the just built toolchain. This is important now for packages such as SwiftSyntax which we build using a pinned toolchain.

build: make `-BuildType RelWithDebInfo -SwiftDebugFormat codeview` work

---

.github/workflows/swift-toolchain.yml

This reverts commit 9e0bcb7917badfab4ecb57ee3c7d2e91043bcc9b.

Revert "GHA: setup sccache to allow better builds"

---

.github/workflows/swift-toolchain.yml

Update to the latest version of actions/checkout.

GHA: update to checkout v4

---

.github/workflows/swift-toolchain.yml

Try to reduce some of the configuration to help reduce the configure time.

GHA: tweak the build tools configure phase

---

docs/WindowsQuickStart.md

Use the new alerts extension in the GitHub flavoured markdown.  This is purely an aesthetic change.

docs: update WindowsQuickStart.md for new GFM

---

.github/workflows/swift-toolchain.yml

Update the setup-python action to upgrade to Node 20.

GHA: update to setup-python@v5

---

.github/workflows/swift-toolchain.yml

Cherry-pick two changes from main to the release/5.10 branch.
Thanks to @hjyamauchi for the reminder!

[5.10] cherry-pick a few fixes for the 5.10 release builds

---

.github/workflows/swift-toolchain.yml

As per https://github.com/thebrowsercompany/swift-build/issues/109#issuecomment-1969309462

GHA: Generate checksums for installers

---

.azure/vs2022.yml

I think it makes sense to unpin VS version in AzDO as in corresponding GHA change in #723

AzDO: unpin VS version

---

default.xml

Based on https://github.com/swiftlang/swift/blob/7eff8fbb44007d60b998eec33e128e30056dc9db/utils/update_checkout/update-checkout-config.json#L114

Update the depedency tags.

---

default.xml

As per https://github.com/swiftlang/swift/blob/7eff8fbb44007d60b998eec33e128e30056dc9db/utils/update_checkout/update-checkout-config.json#L169

Adjust default.xml for release/6.0

---

.github/workflows/swift-toolchain.yml.orig

Cherrypick commit https://github.com/compnerd/swift-build/commit/203d5a020893304c4419ff377ee87eaa497d4875

GHA: update for swift-foundation, swift-foundation-icu

---

.github/workflows/swift-toolchain.yml

Clean up the job names to be consistent throughout.

GHA: tweak some names (NFC)

---

.github/workflows/swift-toolchain.yml

Adjust the paths for the SDK phase, unify the swift-corelibs-foundation checkout.

GHA: adjustments for the SDK phase

---

.github/workflows/build-toolchain.yml

Properly set SQLite version

---

.github/workflows/build-toolchain.yml
.github/workflows/swift-toolchain.yml

* Turn the curl version into an input so it only needs to be set once.

[Mac Build] Build curl on Mac

---

.github/workflows/build-toolchain.yml
.github/workflows/swift-toolchain.yml

* Turn the libxml2 version into an input so it only needs to be set once.

[Mac build] Build libxml2 on Mac

---

.github/workflows/build-toolchain.yml

Updates the swift toolchain to build a newer version of ds2 that contains a number of fixes.

[ds2] update ds2 revision to nightly-2024-09-19

---

.github/workflows/swift-toolchain.yml

This follows https://github.com/swiftlang/swift/commit/ff0f9232aa77f14614a20631364f61fd53d0fb7d

Fix a swift-testing build issue

---

.github/workflows/swift-toolchain.yml

There is no architecture component in the path with the YAML workflow.

GHA: correct the libxml2 path for `LibXml2_DIR`

---

.github/workflows/swift-toolchain.yml

everything is now merged into main.

[workflow] do not use special android ref for scf

---

default.xml

As per https://github.com/swiftlang/swift/blob/9907afa0a0414bef3bbabf795b6748c578004b54/utils/update_checkout/update-checkout-config.json#L174

Update release/6.1 default.xml

---

.github/workflows/swift-toolchain.yml

This was added upstream, follow suite and generate this here as this is needed for packaging.

GHA: generate SDKSettings.json

---

.github/workflows/swift-toolchain.yml

Use download tar artifact for Android stdlib

---

.github/workflows/build-toolchain.yml
.github/workflows/swift-toolchain.yml

Cherry pick commit compnerd/swift-build#878

Get the native arm64 CI to work

---

.github/workflows/build-toolchain.yml
.github/workflows/swift-toolchain.yml

The checkout action was out of date and needed to be updated to the latest.

Update checkout to 4.2.2

---

.github/workflows/swift-toolchain.yml

This modifies the package Android platform job to handle the changes in swiftlang/swift-installer-scripts#406.

Android: Update Android platform packaging

---

.github/workflows/swift-toolchain.yml

libdispatch now installs the files in the right location.

Stop moving the libdispatch swiftmodule files

---

.github/workflows/swift-toolchain.yml

[6.2] Update Android root folder

---

.github/workflows/swift-toolchain.yml

Follow up for Android similar to https://github.com/compnerd/swift-build/pull/1010
Downstream run: https://github.com/thebrowsercompany/swift-build/actions/runs/17077606949

Remove swift flags for Android
